const question = document.querySelector('#question');
const choices = Array.from(document.querySelectorAll('.choice-text'));
const progressText = document.querySelector('#progressText');
const scoreText = document.querySelector('#score');
const progressBarFull = document.querySelector('#progressBarFull');

let currentQuestion = {}
let acceptingAnswers = true
let score = 0
let questionCounter = 0
let availableQuestions = []

let questions = [
{
question:'다음중 네이버 클라우드 플랫폼(M에 없는 상품 카테고리는?',
choice1:' Media',
choice2:' Game',
choice3:' Hybrid & Private Cloud',
choice4:' Market Place',
answer: '4',
			},
		{
question:'현재 네이버 클라우드 플랫폼의 리전으로 제공되지 않는 지역은?',
choice1:' 미국 서부',
choice2:' 미국 동부',
choice3:' 홍콩',
choice4:' 싱가폴',
answer: '2',
			},
		{
question:'다음 상품중 카테고리가 다른 상품은?',
choice1:' GeoLocation',
choice2:' Chatbot',
choice3:' Cloud Outbound Mailer',
choice4:' Source Commit',
answer: '4',
			},
		{
question:'대용량 데이터를 옮기고자 할 때 네트워크 전송이 아닌 이동식 스토리지를 이용하여 데이터를 이전하는 네이버 클라우드 플랫폼 상품은?',
choice1:' Data Teleporter',
choice2:' Data Migration',
choice3:' Data Mover',
choice4:' Data Transfer',
answer: '1',
			},
		{
question:'다음 상품중 카테고리가 다른 상품은?',
choice1:' Effective Log Search & Analytics ',
choice2:' Web Service Monitoring System ',
choice3:' Real User Analytics',
choice4:' Cloud Hadoop',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼 서비스 중에 서버를 확장성 있게 구성하거나 관리할 필요 없이 비즈니스 로직 코드로 서비스를 구성할 수 있는 상품은?',
choice1:' Lambda ',
choice2:' Cloud Functions ',
choice3:' Serverless ',
choice4:' ActiveCode',
answer: '2',
			},
		{
question:'네이버클라우드플랫폼 AI 서비스에서 제공하지 않는 상품은?',
choice1:' Clova OCR ',
choice2:' Clova Image Recognition ',
choice3:' Clova Voice ',
choice4:' Clova Face Recognition',
answer: '2',
			},
		{
question:'고객의 기존 인프라 환경과 네이버 클라우드 플랫폼을 전용선을 이용하여 사설 네트워크로 연결하도록 해주는 상품은?',
choice1:' Lease Line ',
choice2:' Direct Connect ',
choice3:' Active Connect ',
choice4:' Cloud Connect',
answer: '4',
			},
		{
question:'국내 서비스로 한국 대상으로 대용량 파일 다운로드를 하고자 한다. 이 때 현재 사용가능한 적절한 상품은?',
choice1:' CDN ',
choice2:' CDN+',
choice3:' GCDN',
choice4:' GRM',
answer: '2',
			},
		{
question:'Windows 서버의 내 서버 이미지 생성 전 SID 중복으로 발생할 수 있는 오류를 예방하기 위해 해야하는 작업을 바르게 설명한 것을 고르시오',
choice1:' 윈도우 서버 상태를 정지 상태로 만든 후 이미지를 생성한다. ',
choice2:' 윈도우 서버에 할당된 스토리지를 제거한 후 이미지를 생성한다. ',
choice3:' Initialization Tool 01 8 HA sysprep 과정을 거친다. ',
choice4:' 윈도우 서버에 ESC를 사용안함으로 변경한 후 이미지를 생성한다.',
answer: '3',
			},
		{
question:'현재 네이버 클라우드 플랫폼에서 멀티존을 제공하고 있는 리전은?',
choice1:' 일본 ',
choice2:' 한국 ',
choice3:' 독일',
choice4:' 홍콩',
answer: '2',
			},
		{
question:'다음 VPC 환경에서의 Kubernetes Service상품에 대한 설명 중 틀린 것은?',
choice1:' 클러스터 형태로 Kubernetes Service를 제공한다. ',
choice2:' 최대 노드 생성 개수는 20개이다. ',
choice3:' Private Subnet 에서만 생성 가능하다. ',
choice4:' Init Script 적용이 가능하다.',
answer: '2',
			},
		{
question:'유사 서버 생성시 기존 서버의 설정 내용이 반영되는 항목은?',
choice1:' ACG 정보 ',
choice2:' 추가 스토리지 ',
choice3:' Init Script ',
choice4:' 모니터링 설정',
answer: '1',
			},
		{
question:'Object Storage API를 제공하는 리전이 아닌것은?',
choice1:' 미국 서부 ',
choice2:' 싱가포르 ',
choice3:' 독일 ',
choice4:' 홍콩',
answer: '4',
			},
		{
question:'유사 서버 생성시 기존 서버의 설정 내용이 반영되지 않는 항목은?',
choice1:' VPC ',
choice2:' Init Script ',
choice3:' ACG ',
choice4:' 서버 타입',
answer: '2',
			},
		{
question:'VPC환경/Classic 2세대 서버의 Standard 서버 스펙 중 생성 가능한 서버 스펙은 무엇인가요?',
choice1:' VCPU 27H, RAM 8GB ',
choice2:' VCPU 27H, RAM 4GB ',
choice3:' VCPU 27H, RAM 16GB ',
choice4:' VCPU 47H, RAM 4GB',
answer: '1',
			},
		{
question:'NAS 볼륨의 데이터를 스냅샷 이미지 A를 이용하여 복원했을 경우에 대한 설명으로 맞는 것을 고르시오.',
choice1:' A 이후 생성된 스냅샷 이미지는 모두 삭제된다. ',
choice2:' A 이전 생성된 스냅샷 이미지는 모두 삭제된다. ',
choice3:' 모든 스냅샷 이미지가 삭제된다. ',
choice4:' 복원 즉시 삭제할 이미지 선택 팝업창이 뜬다.',
answer: '1',
			},
		{
question:'서버 상세보기에서 확인 가능한 내용이 아닌 것을 고르시요. ',
choice1:' 서버 생성 일시 ',
choice2:' 서버 OS ',
choice3:' 최근 종료 일시 ',
choice4:' 추가된 스토리지 정보',
answer: '3',
			},
		{
question:'다음 중 VPC 환경을 기준으로 하였을 때, Zone에 종속적이지 않은 상품은??',
choice1:' 서버 ',
choice2:' 로드밸런서 ',
choice3:' 서브넷',
choice4:' NAT Gateway',
answer: '2',
			},
		{
question:'리눅스 서버에 추가 스토리지가 10GB 였는데 이를 20GB로 용량을 증설한 경우 기존 스토리지에 있는 데이터를 삭제하지 않고 볼륨을 확장하는 패키지는 무엇인가?',
choice1:' LVM ',
choice2:' Spanned Volume',
choice3:' fdisk ',
choice4:' growpart',
answer: '4',
			},
		{
question:'해외 사용자의 경우 도메인에 접속하는 IP를 보고 해당 국가에 인접한 리전의 서버로 접속시키고자 할 때 사용가능한 상품은?',
choice1:' GCDN. ',
choice2:' Global Route Manager ',
choice3:' GIS ',
choice4:' Load Balancer',
answer: '2',
			},
		{
question:'RAID 1(미러)에 대한 설명 중 맞는 것은?',
choice1:' 단순 볼륨에 비해 쓰기 속도가 뛰어나다. ',
choice2:' 단순 볼륨에 비해 읽기 속도가 뛰어나다. ',
choice3:' 저장공간의 손실이 없다. ',
choice4:' 패리티를 이용한 디스크 복구가 가능하다.',
answer: '2',
			},
		{
question:'내 서버 이미지에 대한 설명중 잘못된 것을 고르시오.',
choice1:' 내 서버 이미지는 Storage 메뉴에서 Storage 단위로 이미지를 생성한다. ',
choice2:' Classic 환경에서는 서버가 정지중인 상태에서만 생성가능하다. ',
choice3:' VPC 환경에서는 서버가 운영중인 상태에서도 생성 가능하다. ',
choice4:' 기존 서버 스펙과 다른 서버 스펙으로 서버를 만들 수 있다.',
answer: '1',
			},
		{
question:'Archive Storage 에 대한 설명으로 맞는 것은?',
choice1:' 자주 read가 일어나는 데이터 저장에 최적합한 스토리지이다. ',
choice2:' 데이터 최소 보관 기간은 90일로 설정되어 있다. ',
choice3:' Swift API를 활용해서 데이터 관리가 가능하다. ',
choice4:' Object Storage와의 연동을 통해 데이터에 대한 라이프 사이클 관리가 불가능하다.',
answer: '3',
			},
		{
question:'다음의 설명을 지칭하는 용어는? “서비스로의 인프라를 의미하며 일반적으로 Computing, Networking, Storage | IT 리소스를 서비스 형태로 사용하는 클라우드 컴퓨팅의 한 종류”',
choice1:' Paas ',
choice2:' laas ',
choice3:' Saas ',
choice4:' Faas',
answer: '2',
			},
		{
question:'서로 다른 용량으로 구성된 디스크로 RAID를 구성할 경우 디스크에서 제공되는 모든 용량을 사용하기 위해 구성 가능한 RAID 레벨은?',
choice1:' RAID0 ',
choice2:' RAID 1 ',
choice3:' RAID 5 ',
choice4:' RAID 1+0',
answer: '1',
			},
		{
question:'MC(Main Console) 상에 보여지는 서버의 호스트 네임을 변경하기 위한 가장 좋은 방법은?',
choice1:' 콘솔에서 서버 이름 변경을 선택하여 호스트명을 변경한다. ',
choice2:' letc/sysconfig/network 파일을 수정한다. ',
choice3:' /etc/sysconfig/hostname을 수정한다. ',
choice4:' 한 번 생성된 서버의 이름은 변경할 수 없다.',
answer: '1',
			},
		{
question:'외부에서 네이버 클라우드 플랫폼 서버에 원격으로 접속할 수 있는 방법으로 잘못된 것을 고르시오.',
choice1:' Classic 환경에서는 포트 포워딩 설정을 통해서 접속할 수 있다. ',
choice2:' 서버 생성 시 자동할당 되는 퍼블릭 도메인을 이용해서 접속할 수 있다. ',
choice3:' SSL VPN을 이용해서 접속할 수 있다. ',
choice4:' 공인 IP를 서버에 할당해서 접속할 수 있다.',
answer: '2',
			},
		{
question:'다음 서버 상품에 대한 설명 중 틀린것은?',
choice1:' Micro 타입의 서버는 이용이 불가능하다. ',
choice2:' Classic과 VPC 환경에 있는 서버들 간 사설망 통신을 불가능하다. ',
choice3:' 그래픽 카드 사용이 필요할 땐 GPU 서버를 이용하면 된다. ',
choice4:' 도커 이미지를 보관할 수 있는 상품으로 Container Bucket이 존재한다.',
answer: '1',
			},
		{
question:'NAS 볼륨에 대한 설명으로 적합한 것은?',
choice1:' NAS 볼륨을 생성하면 NAS 전용 웹페이지 URL이 생성되며, 로그인할 수 있는 ID/PW가 생성된다. ',
choice2:' NAS 스냅샷 이미지는 용량, 기간 제한 없이 생성 가능하다. ',
choice3:' VM에 NAS를 마운트하기 위해서는Private Subnet 생성 후 해당 VM(NAS 마운트 해야할 VM)에 추가 NIC를 등록해야한다. ',
choice4:' NAS 스냅샷은 NAS 볼륨 내 설정한 용량(%)만큼 생성되며, 초과 시 오래된 것부터 삭제처리된다.',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼의 스냅샷 이미지에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 신규 서버를 생성할 수 있다. ',
choice2:' 신규 볼륨을 생성할 수 있다. ',
choice3:' 스냅샷 이미지는 사용에 있어 과금은 발생하지 않는다. ',
choice4:' 네이버 클라우드 플랫폼에서는 스냅샷 이미지를 export 하는 기능을 제공한다.',
answer: '2',
			},
		{
question:'NAS 스토리지에 대한 설명 중 맞는 것은?',
choice1:' NAS를 생성 시 기본적으로 스냅샷이 활성화된다. ',
choice2:' NAS 볼륨의 최대 용량은 10TB이다. ',
choice3:' NAS를 사용하기 위해서는 ACG에서 NAS 와의 포트를 열어주어야한다. ',
choice4:' NAS 용량을 늘이거나 줄일 때의 단위는 50GB이다.',
answer: '2',
			},
		{
question:'Block Storage 에 대한 설명으로 맞는 것은?',
choice1:' 기본 스토리지(=root 볼륨)가 HDD 타입일 경우 추가 스토리지도 HDD만 할당 가능하다. ',
choice2:' 기본 스토리지(=root 볼륨)가 SSD 타입일 경우 추가 스토리지도 HDD만 할당 가능하다. ',
choice3:' 기본 스토리지(=root 볼륨)가 HDD 타입일 경우 추가 스토리지는 SSD만 할당 가능하다. ',
choice4:' 기본 스토리지(=root 볼륨)의 디스크 타입과 무관하게 추가 스토리지는 HDD/SSD 모든 타입 볼륨 할당 가능하다.',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼의 Init Script에 대한 설명을 옳은 것은?',
choice1:' VM 생성 시 최초 1회 구동된다. ',
choice2:' 서버를 리부팅할때마다 구동된다. ',
choice3:' 리눅스 계열 서버의 경우 nodejs 스크립트를 이용해서 작성할 수 있다. ',
choice4:' 윈도우 계열의 서버의 경우 PowerShell을 이용해서 작성할 수 있다.',
answer: '1',
			},
		{
question:'Backup 상품에 대한 설명을 옳은 것은?',
choice1:' 콘솔 [백업 신청하기] 메뉴를 통해서 신청해야한다. ',
choice2:' VM 내부 데이터에 대한 백업은 지원하지 않는다. ',
choice3:' VM 내부 database에 대한 백업은 지원하지 않는다. ',
choice4:' 백업 서비스를 이용하기 위해서는 NCP 콘솔에서 제공하는 별도의 양식을 작성한 후 고객센터에 인입해야한다.',
answer: '4',
			},
		{
question:'베어메탈 서버에 대한 설명중 잘못된 것을 고르시오.',
choice1:' 디스크는 RAID 1+0, RAID 5 중 선택할 수 있다. ',
choice2:' 내 서버 이미지를 사용할 수 없다. ',
choice3:' Ubuntu OS는 제공하고 있지 않다. ',
choice4:' Windows 2012 OS가 제공되고 있다.',
answer: '4',
			},
		{
question:'서버이미지 빌더에 대한 설명중 잘못된 것을 고르시오.',
choice1:' 내부적으로 Packer를 사용한다. ',
choice2:' 추가 스토리지를 붙여서 이미지를 생성할수 있다. ',
choice3:' Script 버전 관리가 가능하다. ',
choice4:' 스크립트는 JavaScript 언어로 작성한다.',
answer: '4',
			},
		{
question:'네이버클라우드플랫폼 VPC 환경 기준, Zone에 종속적인 상품이 아닌 것을 고르시오.',
choice1:' Public Subnet',
choice2:' Private Subnet ',
choice3:' Load Balancer ',
choice4:' NAT Gateway',
answer: '3',
			},
		{
question:'Block Storage 에 대한 설명으로 맞는 것은?',
choice1:' HDD 타입의 경우 1GB 당 30 MAX IOPS를 보장한다. ',
choice2:' HDD 타입의 경우 1GB 당 40 MAX IOPS를 보장한다. ',
choice3:' SSD 타입의 경우 1GB 당 30 MAX IOPS를 보장한다. ',
choice4:' SSD 타입의 경우 1GB 당 40 MAX IOPS를 보장한다.',
answer: '4',
			},
		{
question:'VPC/Classic 2세대 서버의 High Memory 서버 스펙 중 생성가능한 서버 스펙은 무엇인가?',
choice1:' VCPU 47H, RAM 8GB ',
choice2:' VCPU 8개, RAM 8GB ',
choice3:' VCPU 27H, RAM 8GB ',
choice4:' VCPU 167H, RAM 128GB',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼의 서버 이미지 빌더에 대한 설명으로 틀린것을 고르시오',
choice1:' 서버 이미지 생성에 사용되는 Packer용 스크립트를 생성하고 관리하도록 도와주는 상품이다.',
choice2:' 이미지 생성 시 추가 볼륨에 대한 스토리지 설정은 할 수 없다. ',
choice3:' 오픈소스인 Packer를 활용해서 구현한 것이다. ',
choice4:' 템플릿에 대한 버전 관리 기능을 제공한다.',
answer: '2',
			},
		{
question:'김초록은 네이버 클라우드 플랫폼 위에서 매일 밤 12시에 간단한 배치 작업을 돌려야한다. 가장 비용 효율적인 방법은?',
choice1:' Standard 타입 서버를 생성하여 배치 작업을 돌린다. ',
choice2:' High CPU 타입 서버를 생성하여 배치 작업을 돌린다. ',
choice3:' Cloud Function 를 이용하여 배치 작업을 돌린다. ',
choice4:' BareMetal 서버를 생성하여 배치 작업을 돌린다.',
answer: '3',
			},
		{
question:'스냅샷에 대한 설명으로 옳은 것은?',
choice1:' 스냅샷 기능을 이용해서 현재와 동일한 데이터의 서버를 만들 수 있다. ',
choice2:' 스냅샷 기능을 이용해서 현재와 동일한 데이터와 추가 볼륨에 대한 이미지를 만들수 있다. ',
choice3:' 스냅샷 기능을 이용해서 현재와 동일한 데이터의 볼륨을 생성할 수 있다. ',
choice4:' 콘솔에서 제공하는 스케쥴링 스냅샷 기능을 이용해서 Custom 주기로 스냅샷을 생성할 수 있다.',
answer: '3',
			},
		{
question:'Server Image Builder에서 이미지 생성 시 Provisioners를 작성하게 됩니다. Provisioners를 작성하는 포맷은 어떤 포맷으로 작성해야 하나요?',
choice1:' CSV ',
choice2:' JSON ',
choice3:' XML ',
choice4:' HTML',
answer: '2',
			},
		{
question:'Block Storage에 대한 설명으로 맞는 것은?',
choice1:' 볼륨 detach는 아직 제공하지 않는다. (향후 지원 예정) ',
choice2:' 볼륨 detach는 기본 스토리지 (=root 볼륨)에 한해서 제공한다. ',
choice3:' 볼륨 detach 기능은 현재 API를 통해서만 제공한다. ',
choice4:' VM 상태에 따라 볼륨 detach가 불가능할 수 있다.',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 추가 스토리지에 대한 설명으로 적절하지 않는 것을 고르시오',
choice1:' HDD / SSD 두 가지 볼륨을 제공한다. ',
choice2:' 추가 스토리지에 대한 detach 기능을 제공한다. ',
choice3:' 추가 스토리지 용량에 대한 업사이징(확대) 기능을 제공한다. ',
choice4:' 추가 스토리지 용량에 대한 다운사이징(축소) 기능을 제공한다.',
answer: '4',
			},
		{
question:'NAS 스토리지를 생성할 때 최소 용량은 얼마인가?',
choice1:' 100GB ',
choice2:' 500GB ',
choice3:' 1TB ',
choice4:' 5TB',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼의 GPU 서버에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 서버 한 대에 최대 12장의 GPU 카드를 작성할 수 있다. ',
choice2:' GPU Core 단위로 할당 가능하다. ',
choice3:' PCI Pass Through 방식으로 제공한다. ',
choice4:' Telsa P100을 제공한다.',
answer: '3',
			},
		{
question:'네이버 오토스케일링에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 네이버 클라우드 플랫폼의 모든 서버 타입에 대해서 오토 스케일링을 사용할 수 있다. ',
choice2:' 오토스케일링을 통해 스케일 아웃되는 VM들은 네이버 클라우드 플랫폼의 Load Balancer 상품과 연동할 수 있다. ',
choice3:' 오토스케일링에 스케일 인/아웃되는 이벤트에 대한 알람(SMS/Email) 기능을 제공하지 않는다. ',
choice4:' 내 서버 이미지를 오토스케일링 베이스 이미지로 사용할 수 없다.',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 환경에서의 내 서버 이미지에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 내서버이미지를 이용해서 생성한 서버의 사설 IP는 변하지 않는다. ',
choice2:' 내서버이미지 사용에 있어 과금은 발생하지 않는다. ',
choice3:' 내서버이미지는 생성한 리전 이외의 다른리전으로 복제가 불가능하다. ',
choice4:' 내서버이미지는 서버가 운영중인 상태에서도 생성 가능하다.',
answer: '4',
			},
		{
question:'다음 VPC 환경에서의 ACG에 대한 설명 중 틀린 것은?',
choice1:' 서버 NIC에 매핑된다. ',
choice2:' Inbound/Outbound 룰 설정 모두 가능하다. ',
choice3:' 허용/거부 룰 설정이 모두 가능하다. ',
choice4:' 서버 생성 시 필수적으로 매핑해야 하는요소이다.',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 서버에 할당된 추가 스토리지를 detach 할 수 있을 때는?',
choice1:' 네이버 클라우드 플랫폼은 볼륨 detach 기능은 제공하고 있지 않다. ',
choice2:' 서버의 상태와 무관하게 추가 스토리지는 detach 할 수 있다. ',
choice3:' 서버가 “운영 중” 상태라도 서버 내부에서 마운트(mount)만 되지 않았다면 추가 스토리지는 detach할 수 있다. ',
choice4:' 서버 상태가 “정지” 상태라면 추가 스토리지는 detach 할 수 없다.',
answer: '3',
			},
		{
question:'서버에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 다양한 스펙의 상품군이 존재한다. ',
choice2:' VDS는 홍콩에서 제공하고 있지 않다. ',
choice3:' Compact/Standard/High Memory 서버는 모든 리전에서 사용 가능하다. ',
choice4:' Micro 서버는 Classic 환경에서 사용이 가능하다.',
answer: '3',
			},
		{
question:'다음 서버 타입 중 Live Migration이 지원되지 않는 서버 타입은 무엇인지 고르시오.',
choice1:' Standard ',
choice2:' High CPU ',
choice3:' High Memory ',
choice4:' BareMetal',
answer: '4',
			},
		{
question:'서버 상태값에 대한 설명이 옳지 않은 것을 고르시오.',
choice1:' 생성중 - 서버 이미지로부터 서버를 생성하는 단계 ',
choice2:' 부팅중 - 서버 생성이 완료되고 전원이 공급되어 부팅되는 단계 ',
choice3:' 설정중 - 사용자가 서버 설정을 변경하여 변경된 내용이 반영되는 중 ',
choice4:' 종료중 - 서버가 반납된 상태',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 환경에서 서버의 네트워크 환경 특성에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 한 대의 서버에는 최대 3개의 네트워크 인터페이스를 장착할 수 있다. ',
choice2:' 한 대의 서버에는 각기 다른 서브넷 대역의 IP를 여러개 받을 수 없다.',
choice3:' 서버의 사설망 대역은 RFC1918 표준 대역을 따른다. ',
choice4:' 각기 다른 VPC에 속해있는 서버들도 VPC Peering을 통해 서로 통신할 수 있다.',
answer: '2',
			},
		{
question:'RAID 1+0에 대한 설명 중 틀린것은?',
choice1:' 최소 디스크가 2개 이상이어야한다. ',
choice2:' RAID1으로 구성된 볼륨을 RAID으로 구성한다. ',
choice3:' 저장공간의 손실이 50%이다. ',
choice4:' 단순 볼륨에 비해 읽기, 쓰기 속도가 뛰어나다.',
answer: '1',
			},
		{
question:'네이버 클라우드 플랫폼VPC 환경에서 제공되는 GPU 서버의 특징으로 틀린것은?',
choice1:' NVIDIA T4, V100 이용이 가능하다. ',
choice2:' 서버 1대당 꽂을 수 있는 T4의 최대 개수는 2개이다. ',
choice3:' 서버 1대당 꽂을 수 있는 V100의 최대 개수는 4개이다.',
choice4:' Grid 기술을 사용할 수 있다.',
answer: '4',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼에서 CLI를 사용하기 위한 방법으로 올바른 것은?',
choice1:' 서버에 CLI 패키지가 이미 내장되어 있다. ',
choice2:' CLI는 따로 제공되지 않는다. ',
choice3:' CLI 참조서에서 CLI 파일을 다운로드하여 서버에 설치한다. ',
choice4:' 고객센터를 통해 CLI 이용을 신청한다.',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 MC(Main console)에 대한 설명으로 잘못된 것은?',
choice1:' 상품 별 상세 사용 가이드 문서를 제공한다. ',
choice2:' 모바일 콘솔은 제공하지 않는다. ',
choice3:' 사용 중인 상품 이용 내역을 확인할 수 있다. ',
choice4:' 자주 사용하는 상품을 고정할 수 있다.',
answer: '2',
			},
		{
question:'다음 중 네이버 클라우 드 플랫폼에서의 Live Migration에 대한 설 명으로 올바른 것은?',
choice1:' 일반 서버의 경우 호스트 서버 장애 시 Live Migration 이 작동한다. ',
choice2:' BareMetal 서버의 경우 시간이 조금 걸리지만 Live Migration 이 가능하다. ',
choice3:' Live Migration 이란 서버가 죽지 않고 호스트서버가 변경되는 것을 뜻한다. ',
choice4:' Live Migration 기능을 활성화하기 위해서는 서비스 신청이 필요하다.',
answer: '2',
			},
		{
question:'다음 중 분산파일 시스템인 것은 무엇 인가?',
choice1:' EXT3 ',
choice2:' CODA ',
choice3:' NTFS ',
choice4:' JFS',
answer: '2',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼에서 제공하지 않는 상품은?',
choice1:' Container Registry ',
choice2:' HPC ',
choice3:' Organization ',
choice4:' Teleporter',
answer: '4',
			},
		{
question:'Linux에서 LVM을 구성하고자 합니다. Fdisk에서 LVM용 파티션을 구성하려고 하는데 LVM의 파티션 번호는 무엇인가요??',
choice1:'83',
choice2:' e6 ',
choice3:'80',
choice4:' 8e',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 쿠버네티스 워커노드에 설치되지 않는 요소는 무엇인가?',
choice1:' docker ',
choice2:' Rubelet ',
choice3:' controller-manager ',
choice4:' kube-proxy',
answer: '3',
			},
		{
question:'다음 중 CLI를 사용하여 Kubernetes service를 제어할 수 있도록 설치해야 하는 것은?',
choice1:' calico ',
choice2:' kubecti ',
choice3:' ncloud cli',
choice4:' kubelet',
answer: '2',
			},
		{
question:'Object Storage가 일반적인 분산파일시 스템과 다른점은 무엇인가?',
choice1:' 저장 용량에 한계가 없다. ',
choice2:' 장애시에 복구가 가능하다. ',
choice3:' 다양한 접근 경로를 제공한다. ',
choice4:' 파일 단위로 저장 및 복제한다.',
answer: '4',
			},
		{
question:'다음 중 네이버 클라 우드 플랫폼 Kubernetes Service 상품에 대한 설명으로 틀린 것은?',
choice1:' Container Registry 상품과 연동이 가능 하다. ',
choice2:' VPC 플랫폼에서는 워커노드를 최대 50대까지 생성 가능 ',
choice3:' Classic 플랫폼에서는 워커노드를 최대10대까지 생성 가능 ',
choice4:' Master Node에 접근하기 위해서는 pem | key가 필요하다.',
answer: '4',
			},
		{
question:'RAID 0(스트라이프)에 대한 설명 중 틀린 것은?',
choice1:' 단순볼륨에 비해 쓰기 속도가 뛰어나다. ',
choice2:' 단순볼륨에 비해 읽기 속도가 뛰어나다. ',
choice3:' 단순 볼륨에 비해 데이터 안정성이 높다. ',
choice4:' 저장공간의 손실이 없다.',
answer: '3',
			},
		{
question:'Archive Storage에 대한 설명으로 맞는 것은?',
choice1:' 3rd party 툴 없이도 다수의 vm에 마운트하여 사용할 수 있다. ‘',
choice2:' 각 오브젝트 별 URL이 생성된다. ',
choice3:' AWS S3 API를 사용할 수 있다. ',
choice4:' 용량은 최대 40TB 까지이며, 고객센터 문의를 통해 언제든 용량을 무한히 확장할 수 있다.',
answer: '3',
			},
		{
question:'파일시스템중 파일의 시작위치와 크기 를 가지고 데이터를 저장하는 방식으로 고전적인 파일시스템 구조이며 단순하지만 데이터 공간에 대한 낭비가 심한 파일시스템 방식은 무엇인가?',
choice1:' 연속 할당 방식 ',
choice2:' 연결 할당 방식 ',
choice3:' 색인 할당 방식 ',
choice4:' 링크 연결 방식',
answer: '1',
			},
		{
question:'VPC 환경의 Standard 서버 타입 중 지원하지 않는 서버 스펙은?',
choice1:' 2vCPU 8G RAM ',
choice2:' 4vCPU 16G RAM ',
choice3:' 8VCPU 32G RAM ',
choice4:' 12VCPU 64G RAM',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 쿠버네티스 마스터노드에 설치되지 않는 요소는 무엇인가?',
choice1:' etcd ',
choice2:' apiserver ',
choice3:' scheduler ',
choice4:' kubelet',
answer: '4',
			},
		{
question:'다음 중 쿠버네티스의 Pod에 대한 설명으로 틀린 것은?',
choice1:' 쿠버네티스는 Container를 직접 관리한다. ',
choice2:' 애플리케이션의 실행 단위이다. ',
choice3:' 하나의 Pod에는 여러 개의 Container가 구성될 수 있다. ',
choice4:' 쿠버네티스 객체 모델 중 만들고 배포할 수 있는 가장 작고 간단한 단위이다.',
answer: '1',
			},
		{
question:'VPC 플랫폼상의 Kubernetes Service에서는 최대 몇 대의 워커노드 생성이 가능한 가?',
choice1:' 10대',
choice2:' 30대 ',
choice3:' 50대 ',
choice4:' 100대',
answer: '3',
			},
		{
question:'API를 이용하여 Object Storage로 파일을 업로드하려 한다. 이 때 단일 파일의 최대 크기는 얼마인가?',
choice1:' 1TB ',
choice2:' 2TB ',
choice3:' 5TB ',
choice4:' 10TB',
answer: '4',
			},
		{
question:'Linux에서 추가 디스크 용량을 데이터 유실 없이 증설하고자 한다. 추가 디스크의 용량을 증설한 후 어떤 명령어를 사용하여야 하는가?',
choice1:' fdisk ',
choice2:' growpart ',
choice3:' ivm ',
choice4:' mkdisk',
answer: '2',
			},
		{
question:'Object Storage 에 대한 설명으로 옳은것은?',
choice1:' OpenStack Swift API를 사용해 데이터를 관리할 수 있다. ',
choice2:' 데이터 저장 공간은 초기 40TB이며, 특정 양식을 통해 증설할 수 있다. ',
choice3:' 라이프사이클 기능을 통해서 일정 시간이 지난 데이터를 Archive Storage로 데이터 이관이 가능하다. ',
choice4:' 콘솔을 이용해서 업로드 할 수 있는 최대 오브젝트 크기는 2G이다.',
answer: '3',
			},
		{
question:'다음 중 리눅스 서버의 기본 OS 용량은?',
choice1:' 50GB ',
choice2:' 100GB ',
choice3:' 150GB ',
choice4:' 200GB',
answer: '1',
			},
		{
question:'Linux에서 NAS를 마운트 할 때 사용하는 옵션은 무엇인가?',
choice1:' mount -t nas ',
choice2:' mount -text4 ',
choice3:' mount -t nfs ',
choice4:' mount -t net',
answer: '3',
			},
		{
question:'김초록씨는 클라우드 상에서 효과적으로 데이터를 저장하고자 한다. 자주 접근하는 데이터는 000에, 아카이빙 용도의 데이터는 000에 보관해야 한다. 각 000에 맞는 단어가 순차적으로 들어간 보기를 고르 세요.',
choice1:' Object Storage, Block Storage ',
choice2:' Archive Storage, Object Storage ',
choice3:' Object Storage, Archive Storage ',
choice4:' Archive Storage, NAS',
answer: '3',
			},
		{
question:'다음 중 컨테이너 기술에 대한 설명으로 올바른 것은?',
choice1:' 자신이 올라가있는 서버에 있는 커널을 함께 공유한다. ',
choice2:' 효율적이지 못한 기술이다. ',
choice3:' 물리서버 위에서는 3대만 운영이 가능하다. ',
choice4:' 가상서버 위에서는 1대만 운영이 가능하다.',
answer: '1',
			},
		{
question:'File system의 데이터 저장 방식 중에서, 데이터 저장 공간의 비효율성이 존재하는 저장방식은?',
choice1:' 링크 방식 ',
choice2:' 인덱스방식 ',
choice3:' 연속할당 방식 ',
choice4:' 분산저장방식',
answer: '3',
			},
		{
question:'Kubernetes에서 정의하고 있는 가장 기본 단위는?',
choice1:' Pod ',
choice2:' Deployment ',
choice3:' Ingress ',
choice4:' Service',
answer: '1',
			},
		{
question:'도커이미지를 바탕으로 도커를 생성하기 위한 명령어는?',
choice1:' Docker push ',
choice2:' Docker login',
choice3:' Docker build ',
choice4:' Docker run',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫 폼에서 서버를 생성하면 기본 네트워크 링크의 속도는 어떻게 되는가?',
choice1:' 1Gbps ',
choice2:' 100Mbp ',
choice3:' 500Mbps ',
choice4:' 10Gbps',
answer: '1',
			},
		{
question:'고객이 기존에 사용하던 오라클 라이선스를 BYOL 형태로 네이버클라우드플랫폼 서버로 이관하고자 한다. 이때 적합한 서버 타입은?',
choice1:' High-memory server ',
choice2:' Standard server ',
choice3:' VDS ',
choice4:' Bare-metal',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼에서는 다양한 Media 상품을 제공합니다. 다음 중 제공되는 Media 상품이 아닌 것은?',
choice1:' Video Player ',
choice2:' NAVER Player ',
choice3:' Image Optimizer ',
choice4:' VOD Station',
answer: '2',
			},
		{
question:'VPC 환경에서의 ACG에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 지원되는 프로토콜을 TCP, UDP, ICMP이다. ',
choice2:' 최대 50개의 룰을 설정할 수 있다. ',
choice3:' Inbound, Outbound || CHHA ||017 가능하다. ',
choice4:' 서버의 단일 네트워크 인터페이스 카드에는 최대 3개의 ACG를 적용할 수 있다.',
answer: '2',
			},
		{
question:'Container Registry 이용시 이미지를 업로드 하기 위한 docker 명령어는 무엇인가?',
choice1:' docker upload ',
choice2:' docker put ',
choice3:' docker move ',
choice4:' docker push',
answer: '4',
			},
		{
question:'서버 상세보기에서 확인 가능한 내용은?',
choice1:' 관리자 패스워드 ',
choice2:' 설치된 모든 패키지 ',
choice3:' 서버 사양(스펙) ',
choice4:' 네트워크 인터페이스 속도',
answer: '3',
			},
		{
question:' 내서버 이미지에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 내 서버 이미지는 Storage 메뉴에서 Storage 단위로 이미지를 생성한다. ',
choice2:' Classic 환경에서는 서버가 정지중인 상태에서만 생성 가능하다. ',
choice3:' VPC 환경에서는 서버가 운영중인 상태에서도 생성 가능하다. ',
choice4:' 기존 서버 스펙과 다른 서버 스펙으로 서버를 만들 수 있다.',
answer: '1',
			},
		{
question:'Linux에서 LVM 구성을 하고자 한다. LVM 구성이 올바른 명령어 사용 순서는 무엇인가?',
choice1:' pvcreate > fdisk > lvcreate >vgcreate ',
choice2:' Ivcreate > vgcreate > pvcreate > fdisk ',
choice3:' fdisk > pvcreate > vgcreate > Ivcreate ',
choice4:' pvcreate > Ivcreate > fdisk > vgcreate',
answer: '3',
			},
		{
question:'네이버클라우드플랫폼 서버에 대한 설명으로 잘못된 것을 고르시오.',
choice1:' 인증키 분실 시 인증키 변경 기능을 제공한다. ',
choice2:' 공인IP는 서버 당 두 개까지 할당가능하다. ',
choice3:' 리눅스 서버의 경우, 초기 접속 ID는 root이다. ',
choice4:' 서버 최초 접속 시 초기 패스워드는 인증키를 이용해서 확인할 수 있다.',
answer: '2',
			},
		{
question:'NAS 스냅샷의 최대 보관 기간은 얼마인가?',
choice1:' 7일 ',
choice2:' 15일',
choice3:' 24일',
choice4:' 30일',
answer: '1',
			},
		{
question:'다음 중 부팅 디스크가 HDD 일 경우, 추가할 수 있는 block storage의 종류는?',
choice1:' HDD만 가능 ',
choice2:' SSD만 가능 ',
choice3:' HDD, SSD 모두 가능 ',
choice4:' NAS',
answer: '3',
			},
		{
question:'다음 중 도커이미지를 생성하기 위한 Description file을 의미하는 것은?',
choice1:' Dockerfile ',
choice2:' Container file ',
choice3:' Base file ',
choice4:' Description file',
answer: '1',
			},
		{
question:'네이버 클라우드 플랫폼에서 생성한 Linux 서버에서 기본 스토리지의 Device 명은 무엇인가?',
choice1:' /dev/hdd 1',
choice2:' /dev/xvda ',
choice3:' /dev/sda ',
choice4:' /dev/xda',
answer: '2',
			},
		{
question:'NAS에 스냅샷 생성을 설정할 경우 시스템 기본 생성 주기는 무엇인가?',
choice1:' 매일 00:00 ',
choice2:' 매일 04:00',
choice3:' 매일 12:00 ',
choice4:' 매일 08:00',
answer: '1',
			},
		{
question:'쿠버네티스 Service Type에서 가상 머신에 할당된 공인 혹은 사설 IP로 접근하기 위한 Service Type은 무엇인가?',
choice1:' Cluster IP ',
choice2:' LoadBalancer ',
choice3:' NodePort ',
choice4:' ClusterPort',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼 쿠버네티스의 Ingress에 대한 설명으로 틀린것은?',
choice1:' 외부에서 오는 Traffic들을 클러스터 내부의 Service로 라우팅하기 위한 규칙의 집합이다. ',
choice2:' Service 타입 지정은 Node port 혹은 로드밸런서 지정을 하여야 한다. ',
choice3:' NCR은 호스트 기반 및 URL Path 기반 라우팅에 대한 규칙을 사용한다. ',
choice4:' Ingress에 대한 설정은 네이버 클라우드 플랫폼 콘솔에서 설정한다.',
answer: '3',
			},
		{
question:'내 서버 이미지를 통해 윈도우 서버를 새로 생성할 경우, 000을 동작시켜 000를 변경해야 합니다. 각 000에 맞는 단어가 순차적으로 들어간 보기를 고르세요.',
choice1:' sysprp, sid ',
choice2:' sysprep, uuid ',
choice3:' uuidgen, uuid ',
choice4:' uuidchg,uuid',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼의 서버에 대한  설명으로 잘못된 것을 고르시오.',
choice1:' 원하는 만큼 무한정으로 서버를 생성할 수 있다. ',
choice2:' 서버를 정지한 후엔 서버 스펙 변경이 가능하다.',
choice3:' 디스크는 SSD 타입과 HDD 타입을 제공한다',
choice4:' 네이버 클라우드 플랫폼 안의 다른 상품 들과 연계하여 사용이 가능하다.',
answer: '1',
			},
		{
question:'김초록씨는 약 80TB 의 데이터를 온프레미스 환경에서 네이버 클라우드 플랫폼으로 옮겨야 한다. 다음 중 가장 빠르고 안전한 방법은?',
choice1:' Archive Storage 상품을 사용한다',
choice2:' 인터넷을 통해 전송한다.',
choice3:' Data Teleporter 상품을 사용한다',
choice4:' Backup 상품을 사용한다',
answer: '3',
			},
		{
question:'다음 중 VPC 플랫폼 내 서버에 대한 설 명 중 잘못된 것은?',
choice1:' 공인 IP 를 통한 접속이 가능하다 ',
choice2:' SSL-VPN 서비스를 활용하여 서버 접속이 가능하다.',
choice3:' 서버 접속용 공인 IP 를 제공하여, 포트 포워딩 방식으로 접속이 가능하다.',
choice4:' Cloud insight 를 통한 상세모니터링 설정이 가능하다.',
answer: '3',
			},
		{
question:'공인 IP 에 대한 설명 중 틀린 것은?',
choice1:' 서버 1대 당 1개의 공인 IP 만 할당이 가능하다. ',
choice2:' 공인 IP 는 실제 사용하지 않고 발급만 한 상태에선 요금이 부과되지 않는다. ',
choice3:' 외부 인터넷 통신을 필요로 할 때 사용 한다 ',
choice4:' Public Subnet 에 생성된 리소스에 부착 할 수 있다.',
answer: '2',
			},
		{
question:'MC(Main Console) Dashboard 에서 기본 적으로 보여지는 내용이 아닌 것은?',
choice1:' Daily Event ',
choice2:' 결제 정보 ',
choice3:' CPU Top 5 ',
choice4:' 내 서버 장애 내역',
answer: '2',
			},
		{
question:'NAS 볼륨 용량 증설 단위는?',
choice1:' 50GB ',
choice2:' 100GB',
choice3:' 150GB ',
choice4:' 200GB',
answer: '2',
			},
		{
question:'네이버클라우드플랫폼 VPC 환경에서의 내서버이미지에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 내서버이미지를 이용해서 생성한 서버의 사설 IP 는 변하지 않는다. ',
choice2:' 내서버 이미지 사용에 있어 과금은 발생 하지 않는다. ',
choice3:' 내서버 이미지는 생성한 리전 이외의 다른 리전으로 복제가 불가능하다. ',
choice4:' 내서버 이미지는 서버가 운영중인 상태에 서도 생성이 가능하다.',
answer: '4',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼 서버 상품에서 사용 불가능한 OS 항목은? ',
choice1:' Centos ',
choice2:' Fedora ',
choice3:' Windows ',
choice4:' Ubuntu ',
answer: '2',
			},
		{
question:'다음 중 리눅스에서 여러 개의 스토리 지를 하나의 논리적인 볼륨 그룹으로 구성 할 수 있는 것은?',
choice1:' nfs-utils ',
choice2:' 동적디스크 할당 ',
choice3:' LVM ',
choice4:' span volume',
answer: '3',
			},
		{
question:'다음 중 Container registry 에 대한 설명 중 잘못된 것은?',
choice1:' Container registry = private endpoint 제공된다. ',
choice2:' Container registry Object storage 를 근간으로 한다. ',
choice3:' Container registry 에 로그인하기 위해선 access key 와 secrey key 에 대한 정보가 필 요하다 ',
choice4:' Container registry 는 컨테이너 이미지를 저장하고 관리하기 위한 서비스이다.',
answer: '1',
			},
		{
question:'리눅스에서 HTTPD 서버의 로그파일 위 치는 어디인가? (단, 패키지로 설치시)',
choice1:' /var/log/ ',
choice2:' /var/log/apache ',
choice3:' /var/log/httpd ',
choice4:' /var/www/httpd/log',
answer: '4',
			},
		{
question:'다음 중 VPC 플랫폼에서 서버 생성 과 정으로 올바른 순서는? (1). Subnet 생성 (2). 서버 생성 (3). VPC 생성 (4). NACL 생',
choice1:' (1)->(3)->(4)->(2) ',
choice2:' (3)->(4)->(1)->(2) ',
choice3:' (3)->(1)->(4)->(2) ',
choice4:' (1)->(4)->(3)->(2)',
answer: '3',
			},
		{
question:'Kubernetes 에서 service 객체를 통해 만 들어지는 로드밸랜서 타입은?',
choice1:' Network LB',
choice2:' Application LB ',
choice3:' Classic LB ',
choice4:' Network Proxy LB',
answer: '4',
			},
		{
question:'추가 디스크의 용량을 기존 10GB 에서 20GB 로 크기 변경을 하였습니다. 이 때 파 티션 볼륨 할당 정보(10GB / 20G를 확인 할 수 있는 Linux 명령어는 무엇인가요?',
choice1:' df  ',
choice2:' mkfs ',
choice3:' Isblk ',
choice4:' Is',
answer: '3',
			},
		{
question:'다음 중 블록 스토리지의 디스크 타입 변경을 위한 액션으로 적절한 보기는?',
choice1:' 스토리지 디스크 타입을 바로 변경 ',
choice2:' 스냅샷을 생성 후, 스토리지를 생성하며 디스크 타입을 변경 ',
choice3:' 서버를 정지시킨 후 스토리지를 부착시킨 후 스냅샷 생성, 스토리지를 생성하며 디스크 타입을 변경 ',
choice4:' 불가능하다.',
answer: '2',
			},
		{
question:'파일시스템중 네트웍으로 접근 가능한 파일시스템이 아닌 것은 무엇인가?',
choice1:' NFS ',
choice2:' Object Storage ',
choice3:' CIFS',
choice4:' NTFS',
answer: '2',
			},
		{
question:'Micro 서버 타입에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 서버의 사양은 2vCPU.1G RAM, 50GB HDD 이다. ',
choice2:' Classic 환경에서만 이용이 가능하다. ',
choice3:' Windows OS 는 지원하지 않는다. ',
choice4:' 디스크 추가를 할 수 없다.',
answer: '1',
			},
		{
question:' 1PB 는 몇 GB 인가?',
choice1:' 1000GB ',
choice2:' 1024GB',
choice3:' 1000000GB',
choice4:' 1048576GB',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼의 Container  Registry 에 대한 설명중 틀린 것은?',
choice1:' Private EndPoint 구성이 가능하다. ',
choice2:' 도커 레지스트리 HTTPS API V3 를 지원한다. ',
choice3:' Object Storage 를 저장소로 사용한다. ',
choice4:' 컨테이너 취약점 분석 기능을 제공한다.',
answer: '2',
			},
		{
question:'여러 개의 하드디스크에 일부 중복된 데이터를 나눠서 저장하는 기술을 칭하는 단어로 옳은 것은?',
choice1:' RAAD  ',
choice2:' AIDE ',
choice3:' RAID ',
choice4:' AIDR',
answer: '3',
			},
		{
question:'도커이미지를 바탕으로 컨테이너를 생성하기 위한 명령어는?',
choice1:' Docker push ',
choice2:' Docker login ',
choice3:' Docker build  ',
choice4:' Docker run',
answer: '3',
			},
		{
question:'Container Registry 상품에 대한 설명으로 틀린 것은?',
choice1:' 도커 CLI를 이용하여 조작할 수 있다.',
choice2:' Public, Private Endpoint 가 제공된다.  ',
choice3:' 컨테이너 취약점 분석 기능을 제공한다.',
choice4:' 실제 Container 이미지는 BlockStorage 에 보관된다.',
answer: '4',
			},
		{
question:'베어메탈 서버에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 몇 가지 정해진 스펙 군에서 이용이 가능하다. ',
choice2:' 제공되는 OS 로는 Oracle Linux 가 있다. ',
choice3:' CPU 종류 및 코어수를 내가 원하는데로 커스터마이징 할 수 있다. ',
choice4:' 디스크 구성은 RAID 1+0 및 RAID 5로 할 수 있다.',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼에서 서버를 생성하기 위해 미리 VPC설정을 해주어야 합니다. 그 순서로 올바른 것을 고르시오 A. VPC생성 B. Subnet 생성 C. NACL 생성 및 설정   D.ACG 생성 및 설정',
choice1:' B->C->D->A',
choice2:' D->B->C->A',
choice3:' C->B->D->A',
choice4:' A->C->D->B',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 환경의 서버에 대한 설명으로 잘못된 것을 고르시오.',
choice1:' 서버 생성 시 반납 보호 설정으로 삭제를 방지할 수 있다.',
choice2:' 서버 생성 시 선택한 서브넷 대역안에서 원하는 사설 IP를 선택할 수 있다.',
choice3:' 서버 생성 시 한번에 다량의 서버를 만들 수 있다.',
choice4:' 한 번 생성된 VM의 ACG 그룹 변경은 불가능하다.',
answer: '3',
			},
		{
question:' High-CPU 타입으로 서버를 생성하였으나, High-memory로 서버를 스펙업 해야 합니다. 기존 서버의 데이터를 유지하면서 스펙을 변경할 수 있는 방법은 무엇입니까?',
choice1:' High-CPU 서버의 스펙 업그레이드',
choice2:' 서버 이미지 생성 후, 해당 이미지를 바탕으로 High-memory 타입의 서버 생성',
choice3:' 스펙 변경이 불가능하므로, 새로운 서버 생성',
choice4:' 스냅샷 생성 후, High-memory 타입의 서버 생성',
answer: '2',
			},
		{
question:'다음 중 추가 스토리지에 대한 Detach를 할 수 있는 서버의 상태는?',
choice1:' 부팅중',
choice2:' 운영중',
choice3:' 정지',
choice4:' 시작중',
answer: '3',
			},
		{
question:'Block Storage에 대한 설명으로 맞는 것은?',
choice1:' VM 당 최대 10개의 추가 볼륨을 attach 할 수 있다.',
choice2:' VM 당 최대 12개의 추가 볼륨을 attach 할 수 있다.',
choice3:' VM 당 최대 14개의 추가 볼륨을 attach 할 수 있다.',
choice4:' VM 당 최대 15개의 추가 볼륨을 attach 할 수 있다.',
answer: '4',
			}
]

const SCORE_POINTS = 1
const MAX_QUESTIONS = 60

startGame = () => {
    questionCounter = 0
    score = 0
    availableQuestions = [...questions]
    getNewQuestion()

}

getNewQuestion = () => {
    if(availableQuestions.length === 0 || questionCounter >= MAX_QUESTIONS) {
        localStorage.setItem('mostRecentScore', score)

        return window.location.assign('end.html')
    }

    questionCounter++;
    progressText.innerText = `진행도 ${questionCounter}/${MAX_QUESTIONS}`;
    //Update the progress bar
    progressBarFull.style.width = `${(questionCounter / MAX_QUESTIONS) * 100}%`;

    const questionsIndex = Math.floor(Math.random() * availableQuestions.length)
    currentQuestion = availableQuestions[questionsIndex]
    question.innerText = currentQuestion.question

    choices.forEach((choice) => {
        const number = choice.dataset['number'];
        choice.innerText = currentQuestion ['choice' + number];
    })

    availableQuestions.splice(questionsIndex, 1)

    acceptingAnswers = true
}

choices.forEach(choice => {
    choice.addEventListener('click', e => {
        if(!acceptingAnswers) return

        acceptingAnswers = false
        const selectedChoice = e.target
        const selectedAnswer = selectedChoice.dataset['number']

        let classToApply = selectedAnswer == currentQuestion.answer ? 'correct' : 'incorrect'

        if(classToApply === 'correct') {
            incrementScore(SCORE_POINTS)
        }

        selectedChoice.parentElement.classList.add(classToApply)

        setTimeout(() => {
            selectedChoice.parentElement.classList.remove(classToApply)
            getNewQuestion()

        }, 1000)
    })
})

incrementScore = num => {
    score +=num
    scoreText.innerText = score
}

startGame()
