const question = document.querySelector('#question');
const choices = Array.from(document.querySelectorAll('.choice-text'));
const progressText = document.querySelector('#progressText');
const scoreText = document.querySelector('#score');
const progressBarFull = document.querySelector('#progressBarFull');

let currentQuestion = {}
let acceptingAnswers = true
let score = 0
let questionCounter = 0
let availableQuestions = []

let questions = [
 {
question:'D Class IP 주소의 대역은?',
choice1:' 0.0.0.0 - 127.255.255.255',
choice2:' 128.0.0.0 - 191.255.255.255',
choice3:' 224.0.0.0 - 239.255.255.255',
choice4:' 240.0.0.0 - 255.255.255 .255',
answer: '3',
		},
		{
question:'네이버 클라우드 플랫폼의 로드밸런서에 대한 설명으로 옳은 것을 고르시오',
choice1:' Classic 환경에는 총 두 가지 종류의 로드밸런서가 존재한다.',
choice2:' VPC 환경에서는 로드밸런서 생성 시 멀티존 생성이 필수적이다.',
choice3:' 서비스할 프로토콜의 종류에 따라 Application/Network 타입으로 갈라진다.',
choice4:' 세션유지기능이 필요한 경우, Network 로드밸런서를 사용해야 한다.',
answer: '1',
		},
		{
question:'IP헤더에서 TTL은 몇 Bit가 할당되어 있는가?',
choice1:'4',
choice2:'6',
choice3:'8',
choice4:'10',
answer: '3',
		},
		{
question:'다음중 UDP로만 제공되는 서비스는 무엇인가?',
choice1:' DNS 서비스',
choice2:' 넷 바이오스 서비스',
choice3:' NTP 서비스',
choice4:' RPC 서비스',
answer: '3',
		},
		{
question:'네이버클라우드 플랫폼 Global DNS 상품이 지원하는 레코드 타입이 아닌 것을 고르시오',
choice1:' A',
choice2:' NS',
choice3:' CNAME',
choice4:' SOA',
answer: '4',
		},
		{
question:'다음 네개의 상품 중 세개의 상품은 네이버 클라우드 플랫폼의 네트워크망과 외부망간의 통신이 필요로 할 때 사용됩니다. 나머지 이질적인 상품 하나는 무엇인가요?',
choice1:' Cloud CDNnect',
choice2:' Cloud Insight',
choice3:' IPSEC VPN',
choice4:' SSL VPN',
answer:'2',
		},
		{
question:'네이버 클라우드 플랫폼의 VPC 환경에서 ACG룰이 적용되는 장치는 무엇인가요?',
choice1:' 서버',
choice2:' 서버 NIC',
choice3:' IP',
choice4:' Subnet',
answer: '2',
			},
		{
question:'CIDR에서 서브넷이 27bit인 경우 몇 개의 IP를 사용할 수 있는가?',
choice1:'1',
choice2:'6',
choice3:'14',
choice4:'30',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 GRM IP 리소스 타입의 헬스체크 interval로 설정할 수 없는 것을 고르시오.',
choice1:'30',
choice2:'60',
choice3:'120',
choice4:'180',
answer: '3',
			},
		{
question:'다음 중 TCP 프로토콜을 이용하는 서비스가 아닌것을 고르시오.',
choice1:' SSH',
choice2:' FTP',
choice3:' NTP',
choice4:' RDP',
answer: '3',
			},
		{
question:'다음의 설명이 지징하는 용어는?“CDN 캐시서버(엣지서버)에서 캐싱된 데이터를 지우는 기능”',
choice1:' HIT',
choice2:' Streaming',
choice3:' Purge',
choice4:' Cache expiry',
answer: '3',
			},
		{
question:'네이버클라우드 CDN+에 대한 설명으로 잘못된 것을 고르시오',
choice1:' 오리진으로 네이버 클라우드 플랫폼의 Object Storage만 사용할 수 있다.',
choice2:' 국내 서비스에 죄적화된 CDN 상품이다.',
choice3:' 개인 소장 도메인을 CDN 서비스 도메인으로 사용할 수 있다.',
choice4:' CDN도메인을 HTTPS로 사용하기 위해서는 오리진에서도 HTTPS를 지원해야 한다.',
answer: '1',
			},
		{
question:'네이버 클라우드 플랫폼의 로드밸런서에서 제공되지 않는 로드분배 알고리즘은 무엇인가?',
choice1:' Round Robin',
choice2:' Weighted Round Robin',
choice3:' Least Connection',
choice4:' Source IP Hash',
answer: '2',
			},
		{
question:'OSI 7 Layer의 2계층에 해당하는 네트워크 장비는?',
choice1:' 라우터',
choice2:' 로드밸런서',
choice3:' 스위치',
choice4:' 방화벽',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 로드밸런서에서 제공하는 밸런싱 매소드 중 다음이 지칭하는 것을 고르시오. “정적 해쉬 테이블에 있는 소스 IP를 찾아 실제 서버 풀로 요청을 배분하는 방식”',
choice1:' Round-Robin',
choice2:' Weighted',
choice3:' Least-Connection',
choice4:' Source IP hash',
answer: '4',
			},
		{
question:'GRM에서 제공하는 밸런싱 메소드가 아닌 것을 고르시오.',
choice1:' Round Robin',
choice2:' Source IP hash',
choice3:' Weighted',
choice4:' Geolocation',
answer: '2',
			},
		{
question:'210.118.23.45/28 IP 주소의 IP 대역은?',
choice1:' 210.118.23.1 ~ 210.118.23.62',
choice2:' 210.118.23.1 ~ 210.118.23.254',
choice3:' 210.118.20.1~ 210.118.23.254',
choice4:' 210.118.23.32 ~ 210.118.23.47',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 환경에서의 로드밸런서 상품에 대한 설명으로 잘못된 것을 고르시오.',
choice1:' Public Subnet에 생성가능하다.',
choice2:' Application 로드 밸런서는 Proxy 타입이다.',
choice3:' 부하처리 성능에 따라 Small I Medium I Large 중 선택할 수 있다.',
choice4:' 성능은 죄대 9만 CPS까지 자원한다.',
answer: '1',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 환경에서 ACG에 대한 설명으로 틀린것은 무엇인가요?',
choice1:' 서버에 연결되어 있는 맵핑 정보를 변경할 수 있다.',
choice2:' VPC에 의존적이다.',
choice3:' White List 방식의 방화벽이다.',
choice4:' Inbound에 대해서만 룰 적용이 가능하다.',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 VPC 플랫폼의 네트워크 환경에 대한 설명으로 옳은 것을 고르시오.',
choice1:' 서버 당 할당할 수 있는 공인 IP의 최대 갯수는 1개이다.',
choice2:' Private Subnet을 이용해서 외부와 단절된 사설 네트워크를 생성할 수 있다',
choice3:' Private Subnet에서 외부 인터넷으로 연결이 필요한 경우, Internet Gateway를 생성한 후 연동해야한다.',
choice4:' Network Interface의 Secondary IP 기능을 이용하면 HA 솔루션 등에 활용이 가능하다.',
answer: '3',
			},
		{
question:'다음 네이버클라우드 플랫폼 VPC 환경에서의 로드밸런서 상품에 대한 설명 중 틀린것은?',
choice1:' Target Group은 하나 이상의 등록된 대상에 요청을 분배하는데 사용됩니다.',
choice2:' Target Group은 Zone과 Subnet에 상관없이 동일 VPC 내 모든 대상(서버)을 등록할 수 있습니다',
choice3:' Target Group은 편의를 위해 존재하는 상품으로, Target Group 생성 없이도 로드 밸런서에 서버를 연결(bind)할 수 있습니다.',
choice4:' Target Group은 등록 대상에 대하여 정의한 헬스체크를 수행합니다.',
answer: '3',
			},
		{
question:'IP 주소에 해당되는 MAC Address를 얻기 위한 프로토콜은?',
choice1:' ARP',
choice2:' TCP',
choice3:' NTP',
choice4:' FTP',
answer: '1',
			},
		{
question:'다음 중 HA 솔루션 등에 활용하기 위한 보조 IP 기능을 제공해주는 상품 이름은?',
choice1:' Network  lnterface – Secondary IP',
choice2:' Network Interface - HA IP',
choice3:' Server - Secondary IP',
choice4:' Server – HP IP',
answer: '1',
			},
		{
question:'네이버 클라우드 플랫폼 GRM(Global Route Manager)에 대한 설명으로 잘못된 것을 고르시오.',
choice1:' IP, 도메인 리소스에 대한 분기가 가능하다',
choice2:' 도메인 리소스에 대한 헬스체크 설정이 가능하다.',
choice3:' 헬스체크에 대한 로그는 제공하지 않는다.',
choice4:' GRM 리소스 타입은 동일하게 설정해야 한다. (IP와 도메인을 같이 GRM에 바인드할 수 없다.)',
answer: '2',
			},
		{
question:'TCP/IP에서 인터넷 계층에 속하지 않는 프로토콜은?',
choice1:' TCP',
choice2:' IPv4',
choice3:' ARP',
choice4:' IPv6',
answer: '1',
			},
		{
question:'GRM어서 제공하는 메소드 중 다음이 지칭하는 것을 고르시오. “사용자의 캐시 DNS를 기준으로 대륙, 혹은 구간단위 분기가 가능하며, 사용자가 직접 CIDR Map 구성도 가능하다.”',
choice1:' Round Robin',
choice2:' Weighted',
choice3:' Source IP hash',
choice4:' GeoLocation',
answer: '4',
			},
		{
question:'다음 중 포트 번호와 프로토콜이 잘못 짝 지어진 것은?',
choice1:' 22 – SSH',
choice2:' 23 – FTP',
choice3:' 53 – DNS',
choice4:' 143 - imap',
answer: '2',
			},
		{
question:'다음의 설명 중 “이것”이 지칭하는 상품은? “이것을 이용하면 네이버 클라우드 플랫폼 Classic 환경에서 다수 VM에 공인IP를 할당하지 않고 단일 SNAT IP를 쉐어해서 사용할 수 있다.”',
choice1:' 공인 IP',
choice2:' NAT Gateway',
choice3:' CDN+',
choice4:' GRM',
answer: '2',
			},
		{
question:'별도의 설정 없이 클라이언트의 IP를 확인할 수 있는 Load Balancer는 무엇인가?',
choice1:'Classic Load Balancer',
choice2:'Network Load Balancer',
choice3:'Network Proxy Load Balnacer',
choice4:'Application Load Balancer',
answer: '2',
			},
		{
question:'다음 중 Private subnet 에서 외부와 통신하기 위해 추가 생성이 필요한 서비스는?',
choice1:' NAT Gateway',
choice2:' VPC Peering',
choice3:' Internet gateway',
choice4:' Network ACL',
answer: '1',
			},
		{
question:'IP주소에 해당하는 MAC Address를 얻기위한 프로토콜은?',
choice1:' ARP',
choice2:' TCP',
choice3:' NTP',
choice4:' FTP',
answer: '1',
			},
		{
question:'다음 중 TCP 프로토콜을 이용하는 서비스가 아닌것을 고르시오.',
choice1:' SSH',
choice2:' FTP',
choice3:' NTP',
choice4:' RDP',
answer: '3',
			},
		{
question:'다음과 같이 서브넷을 192.168.31.0/23을 만들었다. 그렇다면 IP주소 대역은 어떻게 되는가?',
choice1:' 192.168.31.0 ~ 192.168.31.255',
choice2:' 192.168.30.0 ~ 192.168.31.255',
choice3:' 192.168.31.0 ~ 192.168.32.255',
choice4:' 192.168.0.0 ~ 192.168.255.255',
answer: '2',
			},
		{
question:'L7 헬스체크 기능을 지원하지 않는 로드밸런서 타입은 무엇인가?',
choice1:' Classic Load Balancer',
choice2:' Network Load Balancer',
choice3:' Network Proxy Load Balancer',
choice4:' Application Load Balancer',
answer: '4',
			},
		{
question:'VPC 플랫폼 로드밸런서에서 지원하는 프로토콜의 연결관계가 잘못 짝지어진 것은 무엇인가?',
choice1:' TCP – Network Load Balancer',
choice2:' Proxy TCP – Network Proxy Load Balancer',
choice3:' HTTP – Network Load Balancer',
choice4:' HTTPS – Application Load Balancer',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 GRM에 대한 설명으로 잘못된 것을 고르시오',
choice1:' IP 도메인 리소스에 대한 분기가 가능하다',
choice2:' 도메인 리소스에 대한 헬스체크 설정이 가능하다.',
choice3:' 헬스체크에 대한 로그는 제공하지 않는다.',
choice4:' GRM 리소스 타입은 동일하게 설정해야 한다. (IP와 도메인을 같이 GRM에 바인드 할 수 없다.)',
answer: '2',
			},
		{
question:'다음 중 CDN 서비스에서 콘텐츠에 대한 접근을 제한할 수 있는 것을 고르시오,',
choice1:' Ignore Query String',
choice2:' referrer Domain',
choice3:' BYPASS',
choice4:' Secure-Token',
answer: '4',
			},
		{
question:'다음 중 ACG와 Network ACL의 설명 중 잘못된 것을 고르시오.',
choice1:' Network ACL 과 ACG 모두 Inbound/outbound 룰에 대해 설정이 가능하다.',
choice2:' ACG는 서버당 3개가 적용 가능하다.',
choice3:' ACG는 Defualt로 All deny이나 Network ACL은 All Permit이다.',
choice4:' Network ACL은 서버 NIC 단위로 적용되나, ACG는 Subnet 단위로 적용된다.',
answer: '4',
			},
		{
question:'경로기반 라우팅 기능을 지원하는 Load Balancer 는 무엇인가?',
choice1:' Classic Load Balancer',
choice2:' Network Load Balancer',
choice3:' Network Proxy Load Balancer',
choice4:' Application Load Balancer',
answer: '4',
			},
		{
question:'별도의 설정없이 클라이언트의 IP를 확인할 수 있는 Load Balancer는 무엇인가?',
choice1:' Classic Load Balancer',
choice2:' Network Load Balancer',
choice3:' Network Proxy Load Balancer',
choice4:' Application Load Balancer',
answer: '2',
			},
		{
question:'하나의 VPC에 ACG를 최대 몇 개 까지 생성 가능한가요?',
choice1:' 5개',
choice2:' 100개',
choice3:' 300개',
choice4:' 500개',
answer: '4',
			},
		{
question:'다음의 설명이 지칭하는 용어는? “ CDN 캐시서버(엣지서버)에서 캐싱된 데이터를 지우는 기능”',
choice1:' HIT',
choice2:' Streaming',
choice3:' Purge',
choice4:' Cache Expiry',
answer: '3',
			},
		{
question:'CDN 서비스에서 캐싱된 콘텐츠가 원본서버에 변경되었는지 여부를 확인하는 주기를 지정하는 것은?',
choice1:' referrer',
choice2:' Secure Token',
choice3:' Purge',
choice4:' Cashing Expiry',
answer: '4',
			},
		{
question:'네이버 클라우드 플랫폼 로드밸런서에서 제공하는 밸런싱 매소드 중 다음이 지칭하는 것을 고르시오. “정적 해쉬 테이블에 있는 소스 IP를 찾아 실제 서버의 풀로 요청을 배분하는 방식”',
choice1:' Round-Robin',
choice2:' Weighted',
choice3:' Least-connection',
choice4:' Source IP hash',
answer: '4',
			},
		{
question:'네이버 클라우드 CDN+에 대한 설명으로 잘못 된 것을 고르시오',
choice1:' 오리진으로 네이버 클라우드 플랫폼의 Object Storage만 사용 할 수 없다.',
choice2:' 국내 서비스에 최적화된 CDN 상품이다.',
choice3:' 개인 소장 도메인을 CDN 서비스 도메인으로 사용 할 수 있다.',
choice4:' CDN 도메인을 HTTPS로 사용하기 위해서는 오리진에서도 HTTPS를 지원해야 한다.',
answer: '1',
			},
		{
question:'다음 중 포트번호와 서비스가 잘못 연결된 것을 고르시오.',
choice1:' SSH – 22',
choice2:' Telnet – 23',
choice3:' DNS – 53',
choice4:' IMAP – 93',
answer: '4',
			},
		{
question:'각 계정 당 생성할 수 있는 VPC 갯수는?',
choice1:' 3개',
choice2:' 4개',
choice3:' 5개',
choice4:' 6개',
answer: '1',
			},
		{
question:'다음의 설명 중 “이것”이 지칭하는 상품은?“이것을	이용하면 네이버 클라우드 플랫폼 Classic환경에서 다수 VM에 공인 IP를 할당하지 않고 단일 SNAT IP를 쉐어해서 사용할 수 있다.”',
choice1:' 공인 IP',
choice2:' NAT Gateway',
choice3:' CDN+',
choice4:' GRM',
answer: '2',
			},
		{
question:'VPC 생성시 생성 가능한 IP 주소 범위가 아닌 것은 무엇인가?',
choice1:' 10.0.0.0/12',
choice2:' 192.168.0.0/24',
choice3:' 192.168.0.0/12',
choice4:' 172.168.0.0/16',
answer: '2',
			},
		{
question:'다음과 같이 서브넷 10.0.0.0/15을 만들었다. 그렇다면 IP주소 대역은 어떻게 되는가?',
choice1:' 10.0.0.0 ~ 10.255.255.255',
choice2:' 10.0.0.0 ~ 10.0.255.255',
choice3:' 10.0.0.0 ~ 10.1.255.255',
choice4:' 10.0.0.0 ~ 10.7.255.255',
answer: '3',
			},
		{
question:'GRM의 로드밸렁싱 타입 중, 각 리소스별로 가중치를 주어 요청에 대한 트래픽을 분산하는 방식은?',
choice1:' GeoLocation',
choice2:' Round-robin',
choice3:' Weighted',
choice4:' Fail Over',
answer: '3',
			},
		{
question:'VPC 생성시 생성 가능한 IP주소 범위가 아닌 것은 무엇인가?',
choice1:' 10.0.0.0/8',
choice2:' 127.0.0.0/8',
choice3:' 172.16.0.0/12',
choice4:' 192.168.0.0/16',
answer: '2',
			},
		{
question:'다음 중, 로드밸런서에 SSL인증서를 추가하기 위해 연동해야 하는 서비스는?',
choice1:' SSL Manager',
choice2:' Certificate Manager',
choice3:' SSL-Offload',
choice4:' Global certificate',
answer: '2',
			},
		{
question:'VPC 생성시 생성 가능한 IP 주소 범위가 아닌 것은 무엇인가?',
choice1:' 10.0.0.0/8',
choice2:' 127.0.0.0/8  ',
choice3:' 172.16.0.0/12',
choice4:' 192.168.0.0/16',
answer: '2',
			},
		{
question:'VPC 플랫폼에서 로드밸런서 생성시 Small, Medium, Large 성능을 선택할 수 있습니다. 성능의 기준은 무엇인가요?',
choice1:' 네트워크 대역폭 (bps)',
choice2:' 초당 연결 수 (CPS)',
choice3:' 초당 패킷 수 (PPS)',
choice4:' 리얼서버 대수',
answer: '2',
			},
		{
question:'CDN 서비스에서 원본으로 설정이 가능한 스토리지는?',
choice1:' Archive Storage',
choice2:' Object Storage',
choice3:' Block Storage',
choice4:' NAS',
answer: '2',
			},
		{
question:'다음 중, 네이버클라우드 플랫폼의 로드밸런서 생성시 기본적으로 적용되는 분배 알고리즘은?',
choice1:' Least-cnnection',
choice2:' SourceIP Hash',
choice3:' Round-robin',
choice4:' Weighted',
answer: '3',
			},
		{
question:'CDN 서비스에서 접속자가 요청한 콘텐츠가 유효한 형태로, CDN 캐시서버에 있어 접속자의 요청에 대해서 바로 응답할 때의 상태를 의미하는 것은?',
choice1:' MISS',
choice2:' HIT',
choice3:' BYPASS',
choice4:' Purge',
answer: '2',
			},
		{
question:'VPC 환경에서의 Network Interface에 대한 설명으로 틀린 것은? (확인요망)',
choice1:' 서버 생성시, 최대 3개의 Network Interface 생성이 가능하다.',
choice2:' 각 NIC 에는 Secondary IP 를 부여할 수 있다.',
choice3:' 하나의 NIC에는 최대 3개의 Secondary IP를 추가할 수 있다.',
choice4:' 실제 SeCDNdary IP 활성화를 위해서는 network script를 일부 수정해야 한다.',
answer: '3',
			},
		{
question:'HTTP 2.0 기능을 지원하는 Load Balancer는 무엇인가?',
choice1:' Classic Load Balancer',
choice2:' Network Load Balancer',
choice3:' Network Proxy Load Balancer',
choice4:' Application Load Balancer',
answer: '4',
			},
		{
question:'Private Subnet이 외부와 통신할 수 있도록 (A) 서비스를 추가하였고, Private subnet의 (B)의 Outbound-rule을 수정하여 외부에 통신할시에는 A서비스를 향하도록 수정해야 합니다. A.B에 알맞은 것은?',
choice1:' A - NAT gateway  B – Route table',
choice2:' A – Internet gateway B – Route table',
choice3:' A – Internet gateway B – NACL',
choice4:' A – NAT Gateway B – NACL',
answer: '4',
			},
		{
question:'다음 중 Network ACL에 대한 설명 중 옳은 것을 고르시오.',
choice1:' VPC에 종속적이다.',
choice2:' subnet 단위로 적용이 된다.',
choice3:' default 설정은 all permit 이다.',
choice4:' 설정된 우선순위보다는 모든 규칙을 확인하고 반영한다.',
answer: '4',
			},
		{
question:'이미지 옵티마이저에서 만들어진 섬네일을 호줄하는 URL의 구성요소가 아닌것은?',
choice1:' CDN 도메인',
choice2:' 오브젝트 스토리지 내의파일명',
choice3:' 섬네일 생생 옵션',
choice4:' 토큰키',
answer: '4',
			},
		{
question:'이미지 옵티마이저에서 다음과 같은 쿼리스트링이 의미하는 것이 아닌것은? /파일명.jpg?type=m_wm&w=512&h=1024& bgcolor=000011&wm_path=http://watermark_URL&wm_offx=11&vm_offy=10&wm_alig n=2&anilimit=100&extopt=3',
choice1:' 리사이즈 & 크롭',
choice2:' 가로크기는 512',
choice3:' 워터마크 삽입',
choice4:' 우즉 상단을 기준 가로 11픽셀, 세로 10픽셀 이동하여 워터마크를 찍음',
answer: '1',
			},
		{
question:'VOD Transcoder에 대한 설명 중 틀린 것은?',
choice1:' VOD Transcoder는 CDN과 연계가 가능하다.',
choice2:' Input은 Object Storage를 사용할 수 있다.',
choice3:' 썸네일 설정시 각 Output당 10개의 썸네일이 추출된다.',
choice4:' Output 경로는 File Storage와 Object Storage에 설정할 수 있다.',
answer: '4',
			},
		{
question:'이미지 옵티마이저에서 리사이즈 및 크롭 옵션이 아닌것은?',
choice1:' w',
choice2:' align',
choice3:' bgcolor',
choice4:' faceopt',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 VOD Transcoder에 대한 설명으로 잘못된 것은?',
choice1:' 트랜스 코딩된 파일에 캡션 기능을 제공한다.',
choice2:' 변환 필요 파일은 네이버 클라우드 플랫폼 Object Storage에 있어야 한다.',
choice3:' 트랜스 코딩된 파일은 잡 생성시 지정한 Object Storage 버킷에 저장된다.',
choice4:' Custom Preset 기능을 제공한다.',
answer: '1',
			},
		{
question:'VOD Transcoder 에 대한 설명중 틀린 것은?',
choice1:' Preset은 1~5까지 설정가능하다.',
choice2:' Codec은 H.265만 지원한다.',
choice3:' Thumbnail을 자동생성한다.',
choice4:' Output 경로는 File Storage와 Object Storage에 저장할 수 있다.',
answer: '4',
			},
		{
question:'VOD 트랜스코더에서 Job 생성시 Job 상 태에 대한 설명으로 올바르지 않은 것은?',
choice1:' Fail : 정상적으로 Job이 수행되지 않음',
choice2:' Progressing : Job 수행 중',
choice3:' Submitted : Job 수행 완료',
choice4:' Cancel : Submitted 상태였던 Job 수행 취소',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 Live Station에 대한 설명으로 잘못된 것을 고르시오.',
choice1:' Thumbnail 기능을 제공한다.',
choice2:' CDN+(국내 전용) 상품과의 연동만을 지원한다.',
choice3:' 채널 유지 비용은 발생하지 않는다.',
choice4:' 라이브 영상을 네이버클라우드 플랫폼 Object Storage에 저장할 수 있다.',
answer: '3',
			},
		{
question:'Live Station에서 Output Protocol이 아닌 것은 무엇인가?',
choice1:' HLS',
choice2:' MPEG-DASH',
choice3:' RTMP',
choice4:' RTSP',
answer: '4',
			},
		{
question:'Live Station에서 Input Protocol은 무엇인가?',
choice1:' HLS',
choice2:' MPEG-DASH',
choice3:' RTMP',
choice4:' RTSP',
answer: '4',
			},
		{
question:'이미지 옵티마이저에서 섬네일 생성 규칙을 만드는 방법은?',
choice1:' Query String',
choice2:' Post',
choice3:' Get',
choice4:' URL',
answer: '1',
			},
		{
question:'Image Optimizer의 경우 이미지에 효과를 줄 수 있는 필터 기능을 사용할 수 있습니다. 사용가능한 필터가 아닌것은 무엇인가요?',
choice1:' 샤픈',
choice2:' 블러',
choice3:' 흑백',
choice4:' 파스텔',
answer: '4',
			},
		{
question:'VOD Transcoder에 대한 설명중 틀린 것은?',
choice1:' Video Codec은 H.264, 265가 지원된다.',
choice2:' Audio Codec은 AAC 이다.',
choice3:' 최대 해상도는 720P 이다.',
choice4:' Frame rate는 60까지 지원한다.',
answer: '3',
			},
		{
question:'VOD Station 상품에서 제공되는 DRM 기능과 관련된 설명으로 틀린 것은?',
choice1:' 동영상 파일을 암호화 할 때 사용하는 기술이다.',
choice2:' VOD Station 에서는 자체 DRM 기능을 제공한다.',
choice3:' 불법 다운로드 리스크를 줄일 수 있다.',
choice4:' 3가지 유형이 제공된다.',
answer: '2',
			},
		{
question:'Live Station 상품에서는 다른 플랫폼에 동시 송출을 할 수 있는 기능이 제공됩니다. 이 때 해당 기능을 부르는 명칭은 무엇인가요?',
choice1:' Re-stream',
choice2:' Re-Play',
choice3:' Re-Wind',
choice4:' Re-Watch',
answer: '1',
			},
		{
question:'Image Optimizer 상품에 대한 설명으로 틀린 것은?',
choice1:' Cloud Log Analytics 상품과의 연동이 필수이다.',
choice2:' 변환 Rule의 경우 실제 적용되기까지 약간의 시간이 소요된다',
choice3:' 변환 Rule은 엑셀파일을 통해 다량으로 불러 올 수 있다.',
choice4:' 변환된 이미지 미리보기 기능은 제공되지 않는다',
answer: '4',
			},
		{
question:'Video Player에서 설정 가능한 기능이 아닌 것은 무엇인가?',
choice1:' 재생 속도 조절',
choice2:' 브라우저 최소화시 자동 정지',
choice3:' 자막 지원',
choice4:' 영상 다운로드',
answer: '4',
			},
		{
question:'Live station에서 원본영상을 별도파일로 Storage에 저장하여 보관 할 수 있으며, 현재 라이브중인 영상을 최대 여섯시간전까지 되돌려 볼 수 있는 기능을 사용하기 위해 설정해 줘야 하는 옵션은?',
choice1:' 즉시 녹화 설정',
choice2:' Recording',
choice3:' Stream',
choice4:' DVR 설정',
answer: '4',
			},
		{
question:'VOD Station 상품에 대한 설명으로 틀린 것은?',
choice1:' DRM 기능이 제공된다.',
choice2:' Media Encryption 기능이 제공된다.',
choice3:' 송출할 영상파일은 NAS에 올려야 한다.',
choice4:' HLS, DASH 프로토콜을 지원한다.',
answer: '1',
			},
		{
question:'VOD Station에서 Subtitle Output format은 무엇인가?',
choice1:' VTT',
choice2:' SRT',
choice3:' TTML',
choice4:' CAP',
answer: '1',
			},
		{
question:'VOD Transcoder를 통해 만들어진 영상의 파일 확장자는 무엇인가?',
choice1:' AVI',
choice2:' MP4',
choice3:' MOV',
choice4:' WMV',
answer: '2',
			},
		{
question:'네이버클라우드플랫폼 Cloud DB for My-SOL에서 DB 및 User 생성에 대해 옳은 것은?',
choice1:' 쿼리를 통해 DB 및 User 생성이 가능하다',
choice2:' 쿼리를 통해 DB 생성만 가능하다',
choice3:' 쿼리를 통해 User 생성만 가능하다',
choice4:' 쿼리를 통해 DB와 User를 생성하는 것은 불가능하며, 콘솔을 통해 기능을 제공하고 있다.',
answer: '4',
			},
		{
question:'다음 중, Cloud DB for MS-SOL의 재시작 기능과 관련하여 잘못된 것은?',
choice1:' 재시작을 실행하면 2가지 옵션(Without Fail-over, With Fail-over)가 제공된다.',
choice2:' 재부팅 예약이 가능하다',
choice3:' With Fail-over의 경우, 서비스 다운타임이 짧으며, 사용자가 설정한 SSMS 내용이 그대로 유지된다.',
choice4:' Without Fail-over 옵션 선택 시, 서비스 다운타임이 몇 분 이상 걸릴 수 있다.',
answer: '4',
			},
		{
question:'Cloud DB for MySQL 생성 시 자동 생성되는 항목을 고르시오',
choice1:' Private Domain',
choice2:' ACG',
choice3:' Public Domain',
choice4:' Event History',
answer: '3',
			},
		{
question:'네이버클라우드플랫폼 Cloud DB for MySQL에서 제공하는 이벤트 항목 중 Slow Query Count 항목에 대해 옳은 설명은?',
choice1:' 1초 이상 실행되는 쿼리 개수',
choice2:' 쿼리 요정시간이 2초 이상 걸리는 쿼리 개수',
choice3:' Query_time이 3초 이상 걸리는 쿼리개수',
choice4:' 슬로우쿼리 기준값은 10초이다.',
answer: '1',
			},
		{
question:'다음 중 클래식 플랫폼에서 Preinstall Image로 제공하고 있지 않은 DBMS는?',
choice1:' MariaDB',
choice2:' Redis',
choice3:' Aurora',
choice4:' MSSQL',
answer: '3',
			},
		{
question:'다음중 Cloud DB for MySQL 상품 특징이 아닌것은?',
choice1:' Cloud DB 상품은 고가용성 지원을 설정할 경우, Active master DB와 Standby master DB, 총 2대의 서버가 기본 생성된다',
choice2:' 슬레이브 DB는 데이터베이스의 읽기부하 분산을 위해 생성하는 복제 DB로 한대 단위로 생성된다.',
choice3:' 기본 제공되는 50GB의 디스크는 운영체제를 위한 디스크로 추가 증설이 가능하고, 이용 요금에 포함되지 않음',
choice4:' DB 데이터를 저장하기 위한 데이터 스토리지는 별도로 사용량에 따른 시간 요금으로 과금',
answer: '3',
			},
		{
question:'Cloud DB for MySQL에서 설정할 수 있는 DB이벤트 항목이 아닌것은?',
choice1:' Connections',
choice2:' Slow Query',
choice3:' Replication',
choice4:' Backup',
answer: '4',
			},
		{
question:'Cloud DB for MSSQL에 대한 스토리지에 대한 설명으로 맞는 것은?',
choice1:' 운영체제를 위한 기본 디스크는 50GB가 기본 제공됩니다.',
choice2:' 운영체제가 설치되는 기본 디스크는 용량 변경 불가능합니다.',
choice3:' 최초 DB 생성 시 HDD로만 생성이 가능합니다',
choice4:' 데이터를 저장하기 위한 스토리지 증가 시 50GB단위로 과금됩니다.',
answer: '2',
			},
		{
question:'다음 중 Cloud DB for MySQL에 대한 설명으로 맞는 것은?',
choice1:' 매일 자동으로 DB 백업이 진행되며 최대 6개월까지 보관됩니다.',
choice2:' 최대4대까지 복제 슬레이브 DB 확장이 가능하며 읽기 부하 분산이 가능합니다',
choice3:' 장애 또는 이벤트 발생시 사용자의 메일과 SMS로 빠르게 장애 현황을 알려드립니다',
choice4:' 기본 10GB 데이터 스토리지를 제공하며, 10GB 단위로 3TB까지 자동으로 용량이 증가합니다.',
answer: '3',
			},
		{
question:'Cloud DB for MySQL에 대한 설명으로 틀린것은?',
choice1:' 자동 Fail-over 기능을 제공합니다.',
choice2:' 최대 5대까지 복제 슬레이브 DB 확장이 가능합니다',
choice3:' 매일 자동으로 DB백업이 진행되며 데이터는 최대 30 일까지 보관됩니다.',
choice4:' Slow Query를 해결하기 위한 자동화된 튜닝을 제공합니다',
answer: '4',
			},
		{
question:'현재 네이버클라우드 플랫폼을 통해서 사용할 수 있는 Database Service가 아닌 것은?',
choice1:' Cloud DB for ORACLE',
choice2:' PostgreSQL',
choice3:' Cloud DB for MySQL',
choice4:' MariaDB',
answer: '1',
			},
		{
question:'Cloud DB for MySQL의 백업 기능에 대해 잘못 설명한 것은?',
choice1:' 백업파일은 별도 데이터 스토리지에 저장됩니다.',
choice2:' 사용자가 백업시간을 설정할 수 없으므로, 임의의 시간에 백업이 시작됩니다',
choice3:' 백업 완료 시점 기준의 데이터로 복구가 가능합니다',
choice4:' Stand Alone 서버도 DB백업 및 복구 기능이 사용 가능합니다 .',
answer: '4',
			},
		{
question:'다음 중, Cloud DB for MS-SQL에서 수행 가능한 작업이 아닌 것은?',
choice1:' 재시작 가능',
choice2:' DB Server 삭제',
choice3:' DB Server 일시정지기능',
choice4:' Monitoring',
answer: '3',
			},
		{
question:'다음 중, Cloud DB for MS-SQL 대한 설명중 틀린 것을 고르시오.',
choice1:' Cloud DB for MSSQL 상품의 경우, Standard type과 High-memory 타입을 선택할 수 있습니다.',
choice2:' 데이터 스토리지는 기본 10GB가 자동 할당되며, 10GB 단위로 2TB까지 자동 증가 합니다.',
choice3:' Cloud DB for MSSQL 상품은 Standard 타입에서 High-memory 타입으로 스펙업이 가능합니다.',
choice4:' Cloud DB for MSSQL 상품은 Standalone으로 생성 시, 서버가 1대만 생성됩니다',
answer: '3',
			},
		{
question:'Cloud DB for MySQL에서 각 DB 서버들의 역할을 설명한 것 중 옳지 않은 것은?',
choice1:' Master : 각 DB 서비스의 Master DB역할을 수행중인 DB Server 입니다.',
choice2:' Standby Master : 고가용성을 선택할 경우 Master DB 장애시 생성되며 자동으로 Master로 변경됩니다.',
choice3:' Stand Alone : 고가용성을 선택하지 않을 경우 Stand Alone으로 1대만 생성되며, 장애 시 자동 복구 또는 백업을 지원하지 않습니다. 가급적 개발 DB로 사용을 권장 합니다.',
choice4:' Recovery : 백업으로부터 복구할 경우 Recovery 역할로 생성되며, 데이터 복구를 위해 읽기 전용으로 제공됩니다. Recovery 역할인 DB 서버로 다시 서비스 하고자 할 경우 “신규 DB 서비스 생성”을 통해 서비스 가능한 새로운 DB로 변경할 수 있습니다',
answer: '2',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼 VPC 환경에서의 Cloud DB for Redis 상품에 대한 설명 중 틀린 내용은?',
choice1:' CPU는 기본 4core로 제공된다.',
choice2:' Cluster 기능이 제공된다.',
choice3:' 자동 Fail-Over 기능이 제공된다.',
choice4:' Stand는 최대 20개까지 구성 가능하다.',
answer: '4',
			},
		{
question:'Cloud DB for MySQL으로의 접근 방식에 대한 설명을 잘못된 것은?',
choice1:' 포트포워딩을 이용하여 접근',
choice2:' 네이버클라우드 플랫폼 VM에서 Private 도메인 이용하여 접근',
choice3:' SSL VPN을 이용하여 접근 ',
choice4:' Public 도메인을 이용하여 접근',
answer: '1',
			},
		{
question:'다음중 Cloud DB for MySQL 상품 특징이 아닌것은?',
choice1:' Cloud DB 상품은 고가용성 지원을 설정할 경우,Active master DB와 Standby master DB, 총 2대의 서버가 기본 생성된다.',
choice2:' 슬레이브 DB는 데이터베이스의 읽기 부하분산을 위해 생성하는 복제 DB로 한대 단위로 생성된다.',
choice3:' 기본 제공되는 100GB의 디스크는 운영체제를 위한 디스크로 추가 증설이 가능하고, 이용 요금에 포함되지 않음',
choice4:' DB 데이터를 저장하기 위한 데이터 스토리지는 별도로 사용량에 따른 시간 요금으로 과금',
answer: '3',
			},
		{
question:'Cloud DB for Redis 상품에서 제공되는 CPU Core 개수는?',
choice1:' 1core',
choice2:' 2core',
choice3:' 3core',
choice4:' 4core',
answer: '4',
			},
		{
question:'다음 중, Cloud DB for Redis의 백업 데이터 최대 보관일은?',
choice1:' 5일',
choice2:' 7일',
choice3:' 10일',
choice4:' 14일',
answer: '2',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼 Cloud DB 생성 시에 자동 생성되거나 설정되는 것이 아닌 것은?',
choice1:' Public 도메인',
choice2:' Private 도메인',
choice3:' ACG',
choice4:' Event History',
answer: '1',
			},
		{
question:'다음 중, MS-SQL의 default 접속포트는?',
choice1:'1433',
choice2:'3389',
choice3:'3306',
choice4:'6379',
answer: '1',
			},
		{
question:'Cloud DB for MySQL 상품의 백업에 관련된 내용 중 틀린 것은?',
choice1:' Stand Alone 서버도 DB 백업에 사용할 수 있습니다.',
choice2:' 기본적인 백업이 하루 한번씩 매일 수행되며, 사용자 설정에 따라 최대 30일까지 보관할 수 있습니다',
choice3:' Backup 파일 복원 요청시 신규 VM이 생성되며, DB 서버는 Recovery 모드로 복원되며 데이터 조회만 가능합니다.',
choice4:' 손쉬운 backup방법은 백업요청를 작성하여 신청하고 서버에 Agent를 설치하면 됩니다.',
answer: '4',
			},
		{
question:'Cloud DB for MySQL 설정시 옳지 않은 것은?',
choice1:' MySQL의 기본 포트번호(3306)를 사용하는 것은 보안상 취약할 수 있으므로 변경해서 사용하는 것을 권장합니다.',
choice2:' Cloud DB for MySQL 상품에서 DB서버를 생성하기 위해서는 최조 1회 CLA 상품 사용동의를 하셔야만 합니다.',
choice3:' DB 백업파일 보관 기간을 최소 1일에서 최대 30일까지 선택할 수 있습니다.',
choice4:' 백업파일에 대한 별도의 요금은 부과되지 않습니다',
answer: '4',
			},
		{
question:'Cloud DB for MySQL에 대한 설명으로 옳지 않은 것은?',
choice1:' 다양한 유형의 서버타입을 제공하여 서비스 중에 한 번의 재시작만으로 서버 타입을 변경할 수 있습니다',
choice2:' 네이버 서비스에서 안정성이 검증된 버전을 제공합니다.',
choice3:' 기본 10GB 데이터 스토리지를 제공하며, 10GB 단위로 6TB까지 자동으로 용량이 증가합니다',
choice4:' 마스터DB가 스탠바이 DB로 Fail-over할 때 DNS 방식으로 이중화를 제공함으로써 어플리케이선의 변경이 필요합니다.',
answer: '3',
			},
		{
question:'다음 중, Cloud DB for MySQL에 제공되는 High-memory 타입의 최고 VM사양은?',
choice1:' 16vCPU, 128GB',
choice2:' 32vCPU, 128GB',
choice3:' 32vCPU, 256GB',
choice4:' 48vCPU, 256GB',
answer: '3',
			},
		{
question:'다음 중, Cloud DB for MS-SQL 대한 설명 중 틀린 것을 고르시오',
choice1:' Cloud DB for MSSQL 상품의 경우, Standard type과 High-memory 타입을 선택할 수 있습니다.',
choice2:' 데이터스토리지는 기본 10GB가 자동 할당되며, 10GB 단위로 2TB까지 자동 증가합니다.',
choice3:' Cloud DB for MSSQL 상품은 Standard 타입에서 High-memory 타입으로 스펙업이 가능합니다.',
choice4:' Cloud DB for MSSQL 상품은 Standalone으로 생성 시, 서버가 1대만 생성됩니다.',
answer: '3',
			},
		{
question:'다음 Cloud DB for MSSQL상품의 Slave DB에 대한 설명으로 틀린 내용은?',
choice1:' Slave DB는 log shipping방식으로 생성된다.',
choice2:' 읽기기능 시간을 최대 20시간까지 설정 가능하다.',
choice3:' Slave DB의 스펙을 변경해도, Principal 및 Mirror 서버의 스펙은 변경되지 않는다.',
choice4:' Slave DB는 BI 및 Batch성 작업에 적합하다.',
answer: '3',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼의 DB 서버의 특징으로 올바르지 않은 것은?',
choice1:' 설치형 DB의 경우 클릭 한번으로 HA구성이 가능하다',
choice2:' Cloud DB for MySQL은 스토리지 용량이 최대 6TB까지 자동 증설된다.',
choice3:' Cloud DB for MSSQL의 경우 스토리지 용량이 최대 2TB까지 자동 증설된다.',
choice4:' Cloud DB 상품은 자체 백업기능을 제공한다.',
answer: '1',
			},
		{
question:'다음 Cloud DB for Redis 상품에 대한 설명으로 올바른 것은?',
choice1:' 최근 8주 이내의 모니터링 지표를 확인할 수 있다.',
choice2:' OS Dashboard는 지원되지 않는다.',
choice3:' 백업 기능을 이용하기 위해서는 상품 이용신청서를 작성해야 한다.',
choice4:' 백업은 매일 1번씩 진행되며, 최대 7일까지 보관이 가능하다',
answer: '4',
			},
		{
question:'VPC 환경에서 Cloud DB 상품을 이용할 시 갖는 특징으로 올바르지 않은 것은?',
choice1:' 멀티 존 기능이 지원된다.',
choice2:' 멀티 리전 기능이 제공된다.',
choice3:' Private Subnet에 생성 시 Public 도메인 생성이 불가능하다.',
choice4:' ACG가 자동으로 생성된다.',
answer: '2',
			},
		{
question:'Cloud DB for MySQL 설명으로 틀린 것은?',
choice1:' DB서버의 기본 생성 대수는 고가용성 선택 여부에 따라 달라진다.',
choice2:' 고가용성 선택 시 기본 2대의 DB서버가 생성된다.',
choice3:' Standby Master DB는 평상시에는 동기화 작업외에 다른 용도로 사용 불가하다.',
choice4:' DB서버의 스펙의 변경 시, 마스터 데이터베이스의 스펙만 변경된다.',
answer: '3',
			},
		{
question:'다음 중, Sub Account 에 대한 설명 중 옳지 않은 것은?',
choice1:' Sub account 대시보드에서 서브계정 수, 그룹 수, 정책 수를 확인할 수 있다.',
choice2:' 서브 계정의 정보를 수정 및 삭제는 가능하나 일시정지 기능은 제공되고 있지 않다',
choice3:' 다수의 서브 계정에 동일한 정책이 반영되도록 그룹 기능을 제공한다.',
choice4:' 서브계정들이 이용할 수 있는 권한들을 묶어 정책으로 제공한다.',
answer: '2',
			},
		{
question:'다음 중, WMS에서 측정 가능한 국가가 아닌 곳은?',
choice1:' 가나',
choice2:' 미국',
choice3:' 싱가폴',
choice4:' 일본',
answer: '1',
			},
		{
question:'NCP 모범 사례에 따라 리소스를 프로비저닝하는데 도움이 되도록 실시간 지침을 제공하는 management 상품은?',
choice1:' Organization',
choice2:' Cloud Resource Management',
choice3:' NAVER Cloud Advisor',
choice4:' Cloud Advisor',
answer: '4',
			},
		{
question:'URL만 등록하면 웹 페이지 응답 속도 및 정상 동작 여부를 실시간으로 확인할 수 있으며 사용자가 웹 서비스를 이용하는 행동 패턴을 고려해 시나리오를 작성할 수 있는 네이버 클라우드 플랫폼 서비스는?',
choice1:' Effective Log Search & Analytics(ELSA)',
choice2:' Network Traffic Manitoring',
choice3:' Web service Monitoring System(WMS)',
choice4:' Real User Analytics(RUA)',
answer: '3',
			},
		{
question:'다음 중, WMS 에서 ‘입력한 로그를 포함하고 있는 모든 로그를 필터링’하고 싶을 때 선택하는 필터링 옵션은?',
choice1:' url',
choice2:' urlprefix',
choice3:' js',
choice4:' Jsprefix',
answer: '2',
			},
		{
question:'서브 계정들이 작업한 내역을 볼 수 있는 서비스는?',
choice1:' Cloud Activity Tracer',
choice2:' Account Tracer',
choice3:' Cloud Activity Analytics',
choice4:' Cloud Log Analytics',
answer: '1',
			},
		{
question:'모든 계정의 비용을 통합 결제하고, 모든 계정의 비용을 중앙에서 확인할 수 있으며, 계정별로 이용 가능한 상품과 그 한도를 정책으로 만들어 관리할 수 있도록 도와주는 상품은?',
choice1:' Organization',
choice2:' Sub Account',
choice3:' Cloud Log Analytics',
choice4:' Cloud Account Management',
answer: '1',
			},
		{
question:'다음 중 VPC 플랫폼 기반 Cloud Hadoop 상품의 특징으로 올바른 설명은?',
choice1:' 컴퓨팅 노드와 스토리지 노드가 분리되어 제공된다.',
choice2:' 기본 저장소로 NAS Storage가 제공된다.',
choice3:' 고가용성은 지원되지 않는다',
choice4:' 작업자노드는 최대 4대까지 생성가능하다',
answer: '1',
			},
		{
question:'다음 중 WMS 상품에 대한 내용으로 올바른 것은?',
choice1:' 알람 기능은 제공되지 않는다.',
choice2:' 웨일 브라우저 기반의 테스트만 가능하다',
choice3:' 여러 국가에서의 웹 서비스 응답속도를 확인 할 수 있다',
choice4:' 모니터링은 초 단위로 가능하다.',
answer: '3',
			},
		{
question:'네이버 클라우드 플랫폼 Hadoop Cluster에 포함되지 않은 컴포넌트는 무엇인가요?',
choice1:' HDFS',
choice2:' PRESTO',
choice3:' TAJO',
choice4:' RANGER',
answer: '3',
			},
	{
question:'네이버 클라우드 플랫폼 Hadoop Cluster에 포함된 웹 기반의 관리도구는 무엇인가요?',
choice1:' Hive',
choice2:' Spark',
choice3:' Ambari',
choice4:' Hue',
answer: '3',
			},
		{
question:'다음 중 Sub Account 상품에 대한 설명으로 올바르지 않은 것은?',
choice1:' 다수의 사용자가 동일한 인프라를 이용해야 할 때 사용한다.',
choice2:' 서브계정은 스스로 API Key 발급이 불가능하다.',
choice3:' 2차 인증 설정이 가능하다.',
choice4:' 비밀번호 만료일 설정이 가능하다.',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼의 운영노하우를 바탕으로 도출한 자체 모범사례와 사용자의 이용 내용을 비교 분석하여 좀 더 안전하고 효율적인 서비스가 가능하도록 지원하는 서비스는?',
choice1:' Cloud Consultant',
choice2:' Cloud Advisor',
choice3:' Cloud Tip',
choice4:' Cloud Analysis',
answer: '2',
			},
		{
question:'다음 WMS Monitoring 지표와 관련된 단어들 중, 올바른 뜻풀이가 아닌 것은?',
choice1:' Load Time: 웹페이지를 로딩하는데 걸리는 시간',
choice2:' File Requests: 업로드한 구성요소들의 목록',
choice3:' Scenario: 테스트 시나리오 내용',
choice4:' Today Event: 테스트 URL에서 금일 발생한 이벤트 수',
answer: '2',
			},
		{
question:'네이버 클라우드 플랫폼 Hadoop Cluster에 포함되지 않은 컴포넌트는 무엇인가요?',
choice1:' Zookeeper',
choice2:' Hbase',
choice3:' Impala',
choice4:' Zepplin Notebook',
answer: '3',
			},
		{
question:'다음 중, Cloud Activity Tracer에서 수집된 로그에서 확인할 수 있는 정보가 아닌것은?',
choice1:' 작업내역',
choice2:' 작업상태',
choice3:' 계정유형',
choice4:' 접속내역',
answer: '4',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼에서 제공하는 Analytics 상품이 아닌 것은?',
choice1:' Elasticsearch Service',
choice2:' Cloud Data Streaming Service',
choice3:' Cloud Platform Analytics',
choice4:' Data Analytics Service',
answer: '3',
			},
		{
question:'다음 중, Cloud Activity Tracer 에 대한 설명 중 옳지 않은 것은?',
choice1:' Cloud Activity Tracer는 155개 종류의 네이버 클라우드 플랫폼 계정 활동로그를 자동으로 수집하고 기록합니다.',
choice2:' Cloud Activity Tracer를 사용하기 위해서는 에이전트 설치가 필요합니다.',
choice3:' Cloud Activity Tracer는 CLA와의 연동이 필수적입니다.',
choice4:' Cloud Activity Tracer는 로그 필터링 기능을 제공하고 있습니다',
answer: '3',
			},
		{
question:'서비스 페이지 (PC 또는 웹)에 접속하는 실 사용자 데이터를 수집하여 국가, 브라우저, Device  별로 웹 페이지 속도와 PV Count를 분석해주는 네이버클라우드 플랫폼 서비스는 무엇인지 고르시오.',
choice1:' ELSA',
choice2:' RUA',
choice3:' CLA',
choice4:' WMS',
answer: '2',
			},
		{
question:'다음 Cloud Log Analytics 상품에 대한 설명으로 틀린 것은?',
choice1:' 데이터는 최대 200GB까지 저장 가능하다.',
choice2:' 로그는 Object Storage로 내보낼 수 있다.',
choice3:' 이용하기 위해선 서버에 Agent 설치가 필요하다.',
choice4:' 대시보드를 통해 다양한 데이터를 실시간으로 확인할 수 있다.',
answer: '1',
			},
		{
question:'다음 중, CLA와 연계된 서비스는?',
choice1:' Object Storage',
choice2:' File Storage',
choice3:' NAS',
choice4:' Block Storage',
answer: '1',
			},
		{
question:'다음 중, CLA (Cloud Log Analytics)에 대한 설명으로 잘못된 것은?',
choice1:' Cloud DB for MySQL 로그, 아파치 로그 등이 템플릿으로 제공됩니다.',
choice2:' 고객의 데이터는 논리적으로 분리된 개별 저장소에 2개 이상의 복제본으로 분산 저장됩니다',
choice3:' 저장된 데이터가 100GB를 초과하면 최대 30%까지 과거 데이터부터 매일 삭제될 수 있습니다.',
choice4:' 다른 연계상품을 사용하고 있을 경우에는 연계상품이 해지될때 CLA 데이터가 삭제됩니다.',
answer: '4',
			},
		{
question:'다음 중 네이버 클라우드 플랫폼의 Analytics 상품에 해당되지 않는 것은?',
choice1:' Cloud Data Streaming Service',
choice2:' Cloud Search',
choice3:' Real User Analytics',
choice4:' CAPTCHA',
answer: '4',
			},
		{
question:'CDN서비스의 Access log는 어디에 저장됩니까?',
choice1:' NAS',
choice2:' Archive Storage',
choice3:' Object Storage',
choice4:' Block Storage',
answer: '3',
			},
		{
question:'다음 중 Cloud Advisor 상품의 리포트 기능에서 제공하지 않는 점검 항목은?',
choice1:' NAS 스토리지 ACL 관리',
choice2:' Sub Account의 Access Key 관리',
choice3:' Object Storage 버킷 권한',
choice4:' ACG 포트 관리',
answer: '1',
			},
		{
question:'다음 중 Real User Analytics 상품에 대한 설명으로 틀린 것은?',
choice1:' 대시보드를 통해 최근 300분 이내 발생한 정보 확인이 가능하다.',
choice2:' 데이터 수집을 위해서는 RUA 에서 제공하는 수집코드를 개발코드에 삽입해야 한다.',
choice3:' 프로젝트 단위로 생성이 가능하다.',
choice4:' 대시보드를 통해 직관적인 확인이 가능하다.',
answer: '1',
			},
		{
question:'다음 네 개의 상품 중 세 개의 상품은 네이버 클라우드 플랫폼의 네트워크망과 외부망간의 통신을 필요로 할 때 사용됩니다. 나머지 이질적인 상품 하나는 무엇인가요?',
choice1:' Cloud connect',
choice2:' Cloud Insight',
choice3:' IPSEC VPN',
choice4:' SSL VPN',
answer: '2',
			},
		{
question:'다음 중 Cloud Insight 상품에 대한 내용으로 올바르지 않은 것은?',
choice1:' 감시대상에 대해 알람을 받을 수 있다.',
choice2:' 감시대상 상품은 VPC와 Classic 플랫폼이 상이하다.',
choice3:' 사용자가 별도로 agent 설치를 해야한다.',
choice4:' Notification Recipient 메뉴를 통해 통보 대상자를 생성할 수 있다.',
answer: '3',
			},
		{
question:'다음 중 ELSA(Effective Log Search & Analytics) 상품에 대한 설명으로 틀린 것은?',
choice1:' Mobile App Crash 정보를 쉽게 파악할 수 있게 도와준다',
choice2:' Log Search 항목에서는 로그 수집 정보를 그래프로 확인할 수 있다.',
choice3:' 실시간으로 발생하는 로그를 수집할 수 있다.',
choice4:' 수집된 데이터는 60일 후 삭제된다.',
answer: '4',
			},
		{
question:'다음 중 CLA와 자동으로 연계된 서비스가 아닌 것은?',
choice1:' Server',
choice2:' Cloud DB',
choice3:' Image Optimizer',
choice4:' Object Storage',
answer: '1',
			},
		{
question:'회사정책상 클라우드에서 발생하는 로그를 영구보관해야 한다. 이럴경우, CLA에 설정해줘야 하는 옵션은?',
choice1:' Log expansion를 통해 Object storage상에 로그가 저장될 수 있도록 설정',
choice2:' Archive Log를 통해 Object storage상에 로그가 저장될 수 있도록 설정',
choice3:' Export Log를 통해 Object storage상에 로그가 저장될 수 있도록 설정',
choice4:' Lof stone를 통해 Object storage상에 로그 가 저장될 수 있도록 설정',
answer: '3',
			},
		{
question:'다음 중, CLA (Cloud Log Analytics)에 대한 설명으로 잘못된 것은?',
choice1:' Cloud DB for MySQL 로그, 아파치 로그등이 템플릿으로 제공됩니다.',
choice2:' 고객의 데이터는 논리적으로 분리된 개별 저장소에 2개 이상의 복제본으로 분산 저장됩니다.',
choice3:' 저장된 데이터가 100GB를 초과하면 최대 30%까지 과거 데이터부터 매일 삭제될 수 있습니다.',
choice4:' 다른 연계상품을 사용하고 있을 경우에는 연계상품이 해지될 때 CLA 데이터가 삭제됩니다.',
answer: '4',
			},
		{
question:'다음 중 Cloud Log Analytics 상품에 대한 설명으로 틀린 것은?',
choice1:' 시스템의 로그를 수집하고 분석할 수 있도록 도와주는 상품이다',
choice2:' 네이버 클라우드 플랫폼에서 제공되는 특정 템플릿 로그에 한해 수집이 가능하다',
choice3:' Custom Log 기능을 통해 사용자가 원하는 로그를 지정하여 수집할 수 있다.',
choice4:' 고객의 데이터는 논리적으로 분리된 개별 저장소에 2개 이상의 복제본으로 분산 저장된다.',
answer: '2',
			},
		{
question:'Cloud Insight에 대한 설명 중 잘못된 것을 고르시오.',
choice1:' 선택한 메트릭에 대한 알람레벨은 info,warning,critical로 설정이 가능하다.',
choice2:' 서버와 관련된 메트릭을 수집하기 위해선 에이전트 설치가 필요하다.',
choice3:' 실제 에이전트가 잘 동작하는지 확인하기 위해서 Linux에서는 ps –ef | grep agent 명령어로 확인이 가능하다.',
choice4:' 통보 알람기능을 제공한다.',
answer: '2',
			},
		{
question:'Linux서버에서 시스템 부팅 메시지를 저장하는 로그파일은 무엇인가요?',
choice1:' /var/log/dmesg',
choice2:' /var/log/wtmp',
choice3:' /var/log/access',
choice4:' /var/log/secure',
answer: '1',
			},
		{
question:'리눅스에서 ICMP와 TTL을 이용하여 경로를 확인할 수 있는 프로그램은?',
choice1:' Traceroute',
choice2:' Tracert',
choice3:' Tcpdump',
choice4:' Tcpview',
answer: '1',
			},
		{
question:'Application Load Balancer에서 URL기반으로 분기하기 위한 조건은 무엇인가?',
choice1:' Host Header',
choice2:' Path Pattern',
choice3:' URL Path',
choice4:' URL 라우팅',
answer: '2',
			},
		{
question:'이더넷에서 MTU의 최대사이즈는 몇 바이트인가?',
choice1:'256',
choice2:'1024',
choice3:'1500',
choice4:'64000',
answer: '3',
			},
		{
question:'타 계정과 VPC Peering.시 필요한 정보가 아닌 것은 무엇인가?',
choice1:' 로그인 ID',
choice2:' VPC ID',
choice3:' VPC 명',
choice4:' VPC 네트워크 주소',
answer: '4',
			},
	{
question:'VPC 내에 Public Subnet에 위치시킬 수 없는 Resource는 무엇인가?',
choice1:' Cloud DB for MySQL',
choice2:' 베어메탈 서버',
choice3:' GPU 서버',
choice4:' Kubernetes Service',
answer: '4',
			},
			{
question:'다음 중 로드밸런서의 Target group에 대한 설명 중 틀린 것을 고르시오',
choice1:' 헬스체크 주기는 (5~300초) 이다.',
choice2:' Target Group 안에 있는 서버를 다른 Target Group에 속하게 할 수 있고, Target Group을 다수의 로드밸런서에 연결 할 수 있다.',
choice3:' 동일 VPC내에 있는 서버들에 대해 Target Group을 생성 할 수있다.',
choice4:' 서비스를 수행하는 대상의 프로토콜에 따라 L4 와 L7로 구분 한다.',
answer: '2',
			},
		{
question:'타 계정과 VPC Peering.시 필요한 정보로 옳은 것을 모두 고르시오.',
choice1:' 로그인 ID',
choice2:' VPC ID',
choice3:' VPC 명',
choice4:' VPC 네트워크 주소',
answer: '4',
			},
		{
question:'VPC subnet 속성에 관한 설명 중 틀린 것은?',
choice1:' VPC주소 범위 내에서 CIDR형태로 주소 범위 지정',
choice2:' Zone을 지정할 수 있으며, Zone 내에 한 개의 Subnet만 생성 가능',
choice3:' Public subnet 내에 있는 서버만 Public IP 부여 가능',
choice4:' VPC당 최대 200개의 Subnet 생성 가능',
answer: '2',
			},
	{
question:'Live Station에 대한 설명으로 틀린 것은?',
choice1:' 타임머신(Time Shift)기능으로 놓치지 않는 라이브 방송 서비스를 구현 할 수 있다.',
choice2:' 스트림 상태를 볼 수 있는 모니터링 기능을 제공한다.',
choice3:' 영상을 저장할 수 있는 DVR기능을 제공하며, 저장 가능 한 영상의 길이는 최대 6시간이다.',
choice4:' 트랜스코딩을 통해 화질 변환 없이 송출 한다.',
answer: '4',
			},
		{
question:'Live Station Spec에 관한 설명 중 틀린 것은?',
choice1:' Inputs의 Video Codec은 H.264, H.265를 지원 한다.',
choice2:' Outputs의 Video Codec은 H.264만 지원 한다.',
choice3:' Inputs의 Protocol은 RTMP만 지원 한다.',
choice4:' Outputs Bitrate의 동시 변환 수는 채널당 최대 3개 까지 가능하다.',
answer: '4',
			},
		{
question:'VOD Station에 관한 설명 중 틀린 것은?',
choice1:' Object Storage에 보관된 영상 파일을 이용하여 서비스를 제공한다.',
choice2:' Live Station, VOD Transcoder와 연동하여 사용 가능하다.',
choice3:' CDN 연동을 통해 안정적인 송출이 가능하다.',
choice4:' RTMP 프로토콜을 지원한다.',
answer: '4',
			},
		{
question:'VOD Station 보안 기능 중 틀린 것은?',
choice1:' DRM은 동영상 파일 자체를 암호화 하여 콘텐츠 보안을 강화하고 불법 다운로드 리스크를 줄여준다.',
choice2:' Media Encryption의 암호화 유형은 AES-128이다.',
choice3:' DRM 기능은 콘솔에서 신청 가능하다.',
choice4:' DRM을 적용하기 위해서는 사전에 라이선스를 구매해야 한다.',
answer: '3',
			},
		{
question:'VOD Transcoder에 대한 설명 중 틀린 것은?',
choice1:' 원본 파일을 다양한 디바이스에 맞게 인코딩할 수 있다.',
choice2:' 동시에 최대 10개의 미디어 파일 포맷으로 변환할 수 있다.',
choice3:' 동영상 원본은 반드시 Object Storage에 업로드한 후 해당 원본 영상을 인코딩 하는 방식이다.',
choice4:' Output 설정으로 인코딩할 포맷, 썸네일 설정, 결과파일 저장 경로를 설정할 수 있다.',
answer: '2',
			},
		{
question:'Image Optimizer에서 제공하는 변환 옵션이 아닌 것은?',
choice1:' 자동회전',
choice2:' 얼굴검출',
choice3:' 강제변경',
choice4:' 품질(압축률)',
answer: '3',
			},
		{
question:'Video Player에 관한 설명 중 틀린 것은?',
choice1:' 플레이어 사이즈 옵션은 고정형과 반응형 두개를 지원한다.',
choice2:' 브라우저를 최소화 하면 영상 재생이 자동으로 정지된다.',
choice3:' 자막 지원 기능을 제공하며, 해당 기능은 On/Off가 가능하다.',
choice4:' 재생 속도 조절 기능은 추후 제공 예정이다.',
answer: '4',
			},
		{
question:'Cloud DB for MySQL 설명 중 틀린 것은?',
choice1:' 클릭 몇 번으로 쉽게 데이터베이스 생성 및 구성이 가능하다.',
choice2:' 자동화된 DB백업을 지원한다.',
choice3:' Read Replica 확장이 가능하고, Slave DB는 최대 5개까지 추가 할 수 있다.',
choice4:' 백업 데이터는 최대 30일까지 보관되지만, 백업본 기준 자동 복구 기능은 제공하지 않는다.',
answer: '4',
			},
		{
question:'Cloud DB for MySQL 설명 중 옳은 것은?',
choice1:' 멀티존은 지원하지 않는다.',
choice2:' Private subnet에 구성하는 경우 Public 도메인을 구성할 수 있다.',
choice3:' Public 도메인을 부여해 외부에서 접근이 가능하다.',
choice4:' Master DB서버 2대를 같은 Zone에 생성해 높은 가용성을 제공하다.',
answer: '3',
			},
		{
question:'Cloud DB for MSSQL 설명 중 틀린 것은?',
choice1:' 비용이 저렴한 Standard 버전에서도 자동 Failover를 지원한다.',
choice2:' 어플리케이션 변경 없이 DB고가용성을 지원한다.',
choice3:' 5분단위의 쿼리 레벨 성능 분석을 지원한다.',
choice4:' 백업 보관기간 내 특정 시점으로 복원을 지원한다.',
answer: '3',
			},
		{
question:'Cloud DB for MSSQL의 Slave DB 설명 중 틀린 것은?',
choice1:' 매일 주기적인 BI 및 Batch작업에 적합한 상품이다.',
choice2:' 시간 단위로 읽기 가능한 시간을 최대 16시간까지 설정 가능하다.',
choice3:' Log Shipping 방식으로 생성되며, Transaction Log백업을 Restore하는 동안에는 읽기가 불가능하여 일반 서비스 용도로는 사용 불가능하다.',
choice4:' 읽기 가능 Slave의 Spec을 변경하면 Principal 과 mirror 서버도 함께 변경된다.',
answer: '2',
			},
		{
question:'Sub Account 설명 중 틀린 것은?',
choice1:' 다수의 사용자가 동일한 인프라를 이용하고 관리할 때 사용한다.',
choice2:' 일부 사용자에게 인프라에 대한 한정된 권한을 부여할 때 사용한다.',
choice3:' 네이버 클라우드 플랫폼의 Source Commit을 사용할 때 사용한다.',
choice4:' 권한 부여는 Pre-Defined된 Role에 따른 권한만 부여 가능하다.',
answer: '4',
			},
		{
question:'WMS의 시나리오 기반 모니터링과 관련된 단어들 중 올바른 뜻풀이가 아닌 것은?',
choice1:' 클릭 : 페이지내 링크들을 클릭하는 동작입니다.',
choice2:' 텍스트 입력 : 선택된 오브젝트에 문자열을 입력하는 동작입니다.',
choice3:' 텍스트 검사 : 현재 페이지에서 해당 문자열이 존재하는 지 검사합니다.',
choice4:' 오브젝트 검사 : 현재 페이지에서 선택한 오브젝트가 존재하는 지 검사합니다.',
answer: '1',
			},
		{
question:'WMS의 필터링 기능 중 “입력한 스크립트를 포함하고 있는 모든 스크립트를 필터링 하고 싶을 때” 사용하는 필터링은?',
choice1:' url',
choice2:' urlprefix',
choice3:' js',
choice4:' jsprefix',
answer: '4',
			},
		{
question:'Network Traffic Monitoring 기능 중 틀린 것은?',
choice1:' 사용자의 국가 정보를 기준으로 네트워크 모니터링을 할 수 있어, 고객의 서비스가 어떤 국가에서 많이 사용되는지 확인할 수 있다.',
choice2:' Export기능을 제공하며, DATA(Excel), Image형태로 Export가 가능하다.',
choice3:' 내부망 네트워크 트래픽 정보는 Private Subnet에서 발생한 네트워크 트래픽으로 측정한다.',
choice4:' 원하는 기간을 설정하여 선택된 기간 내에서 모니터링을 필터링하여 확인할 수 있다.',
answer: '3',
			},
		{
question:'Cloud Activity Tracer 설명 중 틀린 것은?',
choice1:' 생성된 계정 활동 로그는 CLA와 연동되어 저장된다.',
choice2:' 메인계정과 서브 계정에 대해 구분하여 검색할 수 있다.',
choice3:' 최근 1일, 1주, 1달, 3달, 1년에 대해 검색 가능하다.',
choice4:' 작업일시, 작업내역, 작업상태, 계정유형, 접속내역등 정보를 확인 할 수 있다.',
answer: '4',
			},
		{
question:'Cloud Insight에서 Event 설정이 불가능한 상품은?',
choice1:' Server',
choice2:' GRM',
choice3:' Cloud DB for Mysql',
choice4:' Cloud Hadoop',
answer: '2',
			},
		{
question:'Cloud Insight 설명 중 틀린 것은?',
choice1:' 이벤트 레벨은 Info, Warning, Critical 중 선택할 수 있고, 발생조건도 설정 가능 하다.',
choice2:' 감시 목적에 따라 감시 항목을 템플릿(Rule Template)으로 생성할 수 있다.',
choice3:' VPC상품의 경우 성능 지표 수집을 위해 Agent가 필요하다.',
choice4:' 리눅스에서 ps -ef | grep insight 명령어로 에이전트가 정상 동작하는지 확인 가능하다. ',
answer: '4',
			},
		{
question:'Cloud Advisor에서 제공하는 점검 항목이 아닌 것은?',
choice1:' Object Storage 버킷 권한',
choice2:' ACG 포트 관리',
choice3:' Cloud DB for Redis 기본 포트 점검',
choice4:' Load Balancer 리스너 보안 관리',
answer: '3',
			},
		{
question:'Organization 설명 중 틀린 것은?',
choice1:' 멤버계정은 Organization에 소속되기 위해서는 마스터 계정의 초대를 받아야 하지만 탈퇴는 자유롭다.',
choice2:' 마스터계정은 다른 계정을 Organization에 초대하거나, Organization의 멤버 계정을 변경 할 수 있다.',
choice3:' 마스터계정은 모든 계정의 사용량 또는 비용을 확인하고 이에 대한 비용을 하나의 청구서로 지불 할 수 있다.',
choice4:' Quata Policy는 마스터 계정이 계정 그룹에 부여한 이용 한도 정책이다.',
answer: '1',
			},
		{
question:'Cloud Log Analytics의 설명 중 틀린 것은?',
choice1:' CLA는 서버에서 발생하는 모든 텍스트형태의 로그를 수집할 수 있다.',
choice2:' 별도의 Agent 설치 없이 바로 사용 가능하다.',
choice3:' Object Storage에 로그를 저장할 수 있지만, Object Storage내 버킷이 없다면 미리 버킷을 생성 해야한다.',
choice4:' Excel파일 형태로도 다운로드 가능하다.',
answer: '2',
			},
		{
question:'RUA(Real User Analytics)의 설명 중 틀린 것은?',
choice1:' 실제 사용자로부터 실시간으로 수집되는 데이터를 통해 웹사이트에서 일어난 다양한 이슈에 대해 효과적으로 대응이 가능하다.',
choice2:' 국가,OS,브라우저,페이지 별 속도정보를 대시보드 그래프를 통해 확인 가능하다.',
choice3:' RUA는 웹사이트내에 코드를 삽입하여 웹사이트의 성능을 측정하여 실시간으로 데이터를 수집한다.',
choice4:' RUA의 요금은 100만PV이하 기준으로 1,000PV당 10원의 요금이 발생한다.',
answer: '4',
			},
		{
question:'ELSA(Effective Log search and Analytics)의 설명 중 틀린 것은?',
choice1:' 대시보드를 통해 실시간으로 발생하는 로그를 확인할 수 있고, 찾고자 하는 로그를 쉽게 검색할 수 있어 장애나 이슈의 원일을 파악하기 용이하다.',
choice2:' ELSA모바일 SDK를 사용하여 앱 크러쉬 정보를 저장하고 분석할 수 있다.',
choice3:' 빠른 필터 기능을 제공해 빠르게 로그 검색이 가능하다.',
choice4:' Log Search에서 기본값으로 현재 시간 기준으로 1시간 동안 발생한 로그에 대해 상세로그 형태로 제공된다.',
answer: '4',
			},
		{
question:'Cloud Hadoop 설명 중 틀린 것은?',
choice1:' 자동으로 클러스터 생성을 지원하여 인프라 관리 작업에 대한 부담이 적다.',
choice2:' 기본 저장소로 Object Storage를 지원하고 Block Storage와도 연동이 가능하다.',
choice3:' 컴퓨팅 노드와 스토리지 노드가 분리돼있다.',
choice4:' 클릭 몇 번 만으로 클러스터 작업자 노드 수를 증거하거나, 축소할 수 있다.',
answer: '2',
			},
		{
question:'Cloud Search 설명 중 틀린 것은?',
choice1:' 형태소 분석처리기 기반으로 정확한 한국어 검색이 가능하다.',
choice2:' 검색 기능을 간편하게 구현할 수 있고, 다양한 인덱싱 구성 방식을 기반으로 검색 환경을 설정할 수 있다.',
choice3:' 컨테이너 타입 중 Small은 문서 200만, 일 쿼리 100만, NAS 100GB, 인덱스 최대 5개',
choice4:' 컨테이너 타입 중 Large는 문서 400만, 일 쿼리 500만, NAS 100GB, 인덱스 최대 10개',
answer: '4',
			},
		{
question:'Cloud Search 리소스 모니터링 용어 중 틀린 것은?',
choice1:' 업로드 된 문서 크기 : 해당 시간에 업로드한 문서의 크기를 보여준다.',
choice2:' Reindex 건수 : 색인변경, 섹션 변경이 일어나기 전 문서의 총 개수를 나타낸다.',
choice3:' API 호출 건수 : 검색 API의 호출 횟수를 의미한다.',
choice4:' 검색 네트워크 사용량 : 검색 API의 네트워크 사용량을 의미한다.',
answer: '2',
			},
		{
question:'Elasticsearch 설명 중 틀린 것은?',
choice1:' 매니저 노드 1대, 데이터 노드 3개로 구성되어 최소 4대의 서버로 구성된다.',
choice2:' 클러스터당 1개의 공인 IP주소가 매니저 노드에 부여된다.',
choice3:' 외부에서 데이터 전송/검색은 공인 IP주소로, 내부에서 데이터 전송/검색은 매니저 노드의 사설 IP주소로 접근하여 이루어진다.',
choice4:' 데이터 노드는 실제 데이터가 저장되는 서버로, 코디네이트 노드로만 통신한다.',
answer: '3',
			},
		{
question:'Cloud Data Streamin Service 설명 중 틀린 것은?',
choice1:' 매니저 노드 1대, 브로커 로드는 최소 3대로 시작한다.',
choice2:' VPC 내부에 구성 해야한다.',
choice3:' 매니저 노드는 Public Subnet에 브로커 노드는 Private Subnet에 생성이 가능하다.',
choice4:' 브로커 노드용 스토리지는 Block Storage를 사용하며, 최대 6TB까지 이용 가능하다.',
answer: '4',
			}
]

const SCORE_POINTS = 1
const MAX_QUESTIONS = 5

startGame = () => {
    questionCounter = 0
    score = 0
    availableQuestions = [...questions]
    getNewQuestion()

}

getNewQuestion = () => {
    if(availableQuestions.length === 0 || questionCounter >= MAX_QUESTIONS) {
        localStorage.setItem('mostRecentScore', score)

        return window.location.assign('end.html')
    }

    questionCounter++;
    progressText.innerText = `진행도 ${questionCounter}/${MAX_QUESTIONS}`;
    //Update the progress bar
    progressBarFull.style.width = `${(questionCounter / MAX_QUESTIONS) * 100}%`;

    const questionsIndex = Math.floor(Math.random() * availableQuestions.length)
    currentQuestion = availableQuestions[questionsIndex]
    question.innerText = currentQuestion.question

    choices.forEach((choice) => {
        const number = choice.dataset['number'];
        choice.innerText = currentQuestion ['choice' + number];
    })

    availableQuestions.splice(questionsIndex, 1)

    acceptingAnswers = true
}

choices.forEach(choice => {
    choice.addEventListener('click', e => {
        if(!acceptingAnswers) return

        acceptingAnswers = false
        const selectedChoice = e.target
        const selectedAnswer = selectedChoice.dataset['number']

        let classToApply = selectedAnswer == currentQuestion.answer ? 'correct' : 'incorrect'

        if(classToApply === 'correct') {
            incrementScore(SCORE_POINTS)
        }

        selectedChoice.parentElement.classList.add(classToApply)

        setTimeout(() => {
            selectedChoice.parentElement.classList.remove(classToApply)
            getNewQuestion()

        }, 1000)
    })
})

incrementScore = num => {
    score +=num
    scoreText.innerText = score
}

startGame()
